refactor(file): improve markup - INNO-1320
ec-europa/europa-component-library pull request #1006
Opened 2019-02-06 15:21 UTC by emeryro

# PR description

Apply improvements discussed in [RFC](https://github.com/ec-europa/europa-component-library/issues/998)

2019-02-06 15:28 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit d70ab8a8c7e9e6893bd210762b58ba5ce1937364

https://deploy-preview-1006--europa-component-library.netlify.com

2019-02-07 07:57 UTC, yhuard requested changes

2019-02-07 07:57 UTC, yhuard commented on src/systems/ec/implementations/react/packages/file/FileDownload.jsx
> +                  hreflang={item.lang}
> Warning: Invalid DOM property `hreflang`. Did you mean `hrefLang`?

2019-02-07 08:52 UTC, yhuard requested changes

2019-02-07 08:52 UTC, yhuard commented on src/systems/ec/implementations/react/packages/file/FileDownload.jsx
> +                  <div className="ecl-file__translation-title" lang={item.lang}>
`lang` should be used only if `item.lang` is a non-empty string

btw `item.lang` is missing in the props validation

2019-02-07 12:57 UTC, yhuard approved these changes

2019-02-07 12:57 UTC, merged