feat(ecl-editor): enhance ECL Editor helper - INNO-1446
ec-europa/europa-component-library pull request #1091
Opened 2019-04-19 14:14 UTC by yhuard

2019-04-19 14:24 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 00e7fd00118cf8724b5e1a49bdb3f90cab419e81

https://deploy-preview-1091--europa-component-library.netlify.com

2019-04-19 14:30 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 9fe85100a4624ded06ae02c30d0338fe3145373a

https://deploy-preview-1091--europa-component-library.netlify.com

2019-04-23 08:39 UTC, degliwe requested changes

2019-04-23 08:39 UTC, degliwe commented on src/generic/generic-style-typography-paragraph/generic-style-typography-paragraph--editor.scss
> +  .ecl-edtior * {
```suggestion
  .ecl-editor * {
```

2019-04-23 09:04 UTC, degliwe approved these changes

2019-04-23 09:04 UTC, merged