feat(message): add print css - INNO-1467
ec-europa/europa-component-library pull request #1102
Opened 2019-04-30 12:40 UTC by emeryro

# PR description

Add print css for Message

2019-04-30 12:52 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit b8ba29bc770c9924c514ac63233ef1ccd5f53e87

https://deploy-preview-1102--europa-component-library.netlify.com

2019-04-30 13:17 UTC, yhuard reviewed
my only concern is about the use of `px` in print... shouldn't we use `pt`?

What are the best practices regarding units (relative vs absolute) in print?

Rephrased: do we want to give to the user the possibility to scale the font/spacing (using relative units) in print or do we enforce the scale?

https://gist.github.com/basham/2175a16ab7c60ce8e001#css-units

2019-05-02 12:52 UTC, yhuard requested changes

2019-05-02 12:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-message/ec-component-message-print.scss
> +@mixin ecl-message-print($boder-width: 1.5pt) {
I'd rather use `mm` or `cm` here

- typography: `pt`
- spacing and other measures: `mm`, `cm`

wouldn't it be better this way?

2019-05-03 09:22 UTC, yhuard approved these changes

2019-05-03 09:22 UTC, merged