feat(stack): add stacks - INNO-1492
ec-europa/europa-component-library pull request #1129
Opened 2019-05-16 14:15 UTC by yhuard

2019-05-16 14:25 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 21ad39df3f1bd53d967dc23816726cdbaa75705b

https://deploy-preview-1129--europa-component-library.netlify.com

2019-05-20 09:09 UTC, emeryro requested changes
I wonder who is the target of this documentation...
This is mostly an "how to use CSS flexbox" description. Is it the role of ECL to teach such things?
Can't we have just a few generic stack examples (the most used ones), and maybe a link to this full documentation if needed?
I fear that it would be too long and complex to read.

2019-05-20 09:09 UTC, emeryro commented on src/systems/ec/implementations/react/utilities/stacks/stories/Index.jsx
> +        Baseline: 'baseline',
`align-items: baseline` displays the items centered on the demo, where it should be at baseline.

2019-05-20 10:13 UTC, yhuard commented on src/systems/ec/implementations/react/utilities/stacks/stories/Index.jsx
> +        Baseline: 'baseline',
where's the baseline in the demo? at the center :)

one easy way to verify it is to remove `align-items: center;` from the box "11"

![image](https://user-images.githubusercontent.com/3524389/58014226-a7f77000-7af8-11e9-9242-454a70eb8880.png)
 
now the difference is obvious 😄

2019-05-20 10:21 UTC, yhuard commented
> This is mostly an "how to use CSS flexbox" description.

In the context of the ECL, i.e. with the utilities provided by the ECL, not everything that flexbox allows to do is possible. On the other hand, most (if not all) ECL utilities are described here. You know what you can do with the ECL utilities (and you learn about flexbox :) ).

> the most used ones

what are the most used stacks? most used by whom?

when we'll start making "compositions" (under "Templates"), we'll probably create some complex layouts, we'll need the full potential of these utilities

2019-05-20 14:05 UTC, emeryro approved these changes

2019-05-20 14:06 UTC, merged