refactor(button): apply latest specs - INNO-1500
ec-europa/europa-component-library pull request #1135
Opened 2019-05-27 06:59 UTC by emeryro

# PR description

Apply [latest specs](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Button+Design+Specifications) for buttons

2019-05-27 07:09 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 076ae8c54c245b5cbf5af233085c1f42f23dbab7

https://deploy-preview-1135--europa-component-library.netlify.com

2019-05-27 07:19 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit c95da600fe575ca9351b850d2ac7cf151e023ec0

https://deploy-preview-1135--europa-component-library.netlify.com

2019-05-27 12:18 UTC, yhuard requested changes
The new specs look properly applied.

There's still "Ghost button" in the docs ("Button name" column), could you update it? Thanks

2019-05-27 13:24 UTC, yhuard approved these changes

2019-05-28 06:04 UTC, yhuard requested changes

2019-05-28 06:04 UTC, yhuard commented on src/systems/eu/implementations/react/components/button/stories/Index.jsx
> +        variant="text"
the variant is still `ghost`

2019-05-28 06:04 UTC, yhuard commented on src/systems/ec/specs/components/button/demo/data--ghost.js
> +  label: 'Text button',
you forgot to rename it in the EU system as well

2019-05-28 06:36 UTC, yhuard approved these changes

2019-05-28 06:36 UTC, merged