refactor(text-field): update styling of text fields - INNO-1593
ec-europa/europa-component-library pull request #1183
Opened 2019-07-01 13:33 UTC by yhuard

2019-07-01 13:43 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 9ba1801080e463ca7542fd64c9c417924e43602e

https://deploy-preview-1183--europa-component-library.netlify.com

2019-07-24 12:42 UTC, emeryro requested changes
firefox adds an extra box-shadow for required textarea, we should remove it
![image](https://user-images.githubusercontent.com/25579221/61794347-4bc70a00-ae21-11e9-83fd-bdffa2ad9430.png)

2019-07-24 12:42 UTC, emeryro commented on src/systems/ec/implementations/vanilla/packages/ec-component-form-text-area/ec-component-form-text-area.scss
> +  .ecl-text-area--md {
we should use the same naming convention for classes as in other components.
so `ecl-text-area--s`, `ecl-text-area--m`, `ecl-text-area--l`

2019-07-24 12:42 UTC, emeryro commented on src/website/src/pages/ec/components/forms/text-field/docs/code.mdx
> +
We should add a paragraph about field sizes on this page

2019-07-24 12:42 UTC, emeryro commented on src/systems/ec/implementations/vanilla/packages/ec-component-form-text-area/ec-component-form-text-area.scss
>      width: 100%;
I guess there should not be a forced width here

2019-07-24 14:07 UTC, emeryro approved these changes

2019-07-24 14:07 UTC, merged