fix(inpage-nav): fix styles - INNO-1609
ec-europa/europa-component-library pull request #1186
Opened 2019-07-03 10:31 UTC by yhuard

2019-07-03 10:42 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit e576c282ba46d2c563d7d13ee9dc7ebb55bfea12

https://deploy-preview-1186--europa-component-library.netlify.com

2019-07-03 10:52 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 677b3225c7261a7b39412ba36aa37975c1814742

https://deploy-preview-1186--europa-component-library.netlify.com

2019-07-03 13:03 UTC, emeryro requested changes

2019-07-03 13:03 UTC, emeryro commented on src/systems/ec/implementations/vanilla/packages/ec-component-inpage-navigation/ec-component-inpage-navigation.scss
> +      background: transparent;
```suggestion
      background-color: transparent;
```

2019-07-03 13:03 UTC, emeryro commented on src/systems/eu/implementations/vanilla/packages/eu-component-inpage-navigation/eu-component-inpage-navigation.scss
> +      background: transparent;
```suggestion
      background-color: transparent;
```

2019-07-04 08:17 UTC, emeryro approved these changes

2019-07-04 08:17 UTC, merged