refactor(accordion): split component - INNO-1562
ec-europa/europa-component-library pull request #1194
Opened 2019-07-09 13:23 UTC by emeryro

# PR description

Split accordion and accordion2 into 2 components.

2019-07-09 13:36 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 8931f0940f5bd5bb36823b434e48c82fb9964491

https://deploy-preview-1194--europa-component-library.netlify.com

2019-07-10 09:46 UTC, yhuard requested changes

2019-07-10 09:46 UTC, yhuard commented on src/systems/ec/specs/components/accordion2/demo/data.js
> +        iconShape: 'general--digital',
is `iconShape` actually used?

2019-07-10 09:46 UTC, yhuard commented on src/systems/eu/implementations/react/components/accordion/stories/Index.jsx
> +        code: `<link rel="stylesheet" type="text/css" href="./styles/ecl-ec-preset-legacy-website.css" />`,
```suggestion
        code: `<link rel="stylesheet" type="text/css" href="./styles/ecl-eu-preset-legacy-website.css" />`,
```

2019-07-10 09:46 UTC, yhuard commented on src/systems/eu/implementations/react/components/accordion/stories/Index.jsx
> +        code: `<link rel="stylesheet" type="text/css" href="./styles/ecl-ec-preset-legacy-website-print.css" />`,
```suggestion
        code: `<link rel="stylesheet" type="text/css" href="./styles/ecl-eu-preset-legacy-website-print.css" />`,
```

2019-07-10 11:14 UTC, emeryro commented on src/systems/ec/specs/components/accordion2/demo/data.js
> +        iconShape: 'general--digital',
not in accordion2 indeed, good catch

2019-07-10 11:54 UTC, yhuard approved these changes

2019-07-10 11:55 UTC, merged