refactor(timeline): split component - INNO-1563
ec-europa/europa-component-library pull request #1195
Opened 2019-07-10 09:40 UTC by emeryro

# PR description

Split timeline and timeline2 into two components

2019-07-10 09:51 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit d3d2561909ca7897277aece911d94f11bf7d682c

https://deploy-preview-1195--europa-component-library.netlify.com

2019-07-10 13:01 UTC, yhuard requested changes

2019-07-10 13:01 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2.js
> +export class Timeline {
```suggestion
export class Timeline2 {
```

2019-07-10 13:01 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2.js
> +export default Timeline;
```suggestion
export default Timeline2;
```

2019-07-10 13:01 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2.js
> +export class Timeline {
otherwise there will be a naming collision

2019-07-10 13:01 UTC, yhuard commented on src/systems/eu/implementations/react/components/timeline2/index.js
> +export default from './src/Timeline2';
can you also `export Timeline2 from './src/Timeline2';` please? :)

2019-07-10 13:01 UTC, yhuard commented on src/systems/eu/implementations/vanilla/packages/eu-component-timeline2/eu-component-timeline2.js
> +export class Timeline {
```suggestion
export class Timeline2 {
```

2019-07-10 13:01 UTC, yhuard commented on src/systems/eu/implementations/vanilla/packages/eu-component-timeline2/eu-component-timeline2.js
> +    // Retro compatibility
do we still need it?

2019-07-10 13:01 UTC, yhuard commented on src/systems/eu/implementations/vanilla/packages/eu-component-timeline2/eu-component-timeline2.js
> +export default Timeline;
```suggestion
export default Timeline2;
```

2019-07-10 13:01 UTC, yhuard commented on src/systems/ec/implementations/react/components/timeline/index.js
>  export default from './src/Timeline';
can you also `export Timeline from './src/Timeline';` please? :)

2019-07-10 13:01 UTC, yhuard commented on src/systems/ec/implementations/react/components/timeline2/index.js
> +export default from './src/Timeline2';
can you also `export Timeline2 from './src/Timeline2';` please? :)

2019-07-10 13:01 UTC, yhuard commented on src/systems/eu/implementations/react/components/timeline/index.js
>  export default from './src/Timeline';
can you also `export Timeline from './src/Timeline';` please? :)

2019-07-11 07:43 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-timeline2/ec-component-timeline2.js
> +      buttonSelector: buttonSelector = '[data-ecl-timeline-button]',
we should have renamed it `data-ecl-timeline2`... but now is too late I guess :'(

2019-07-11 07:50 UTC, yhuard approved these changes
LGTM 👍

2019-07-11 07:50 UTC, merged