docs(message): update documentation of messages - INNO-1635
ec-europa/europa-component-library pull request #1207
Opened 2019-07-15 12:27 UTC by yhuard

https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Messages+-+ECL+Page+-+final

2019-07-15 12:39 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit dbcb260ddb471149711442db959446b835cab05a

https://deploy-preview-1207--europa-component-library.netlify.com

2019-07-16 11:35 UTC, emeryro requested changes

2019-07-16 11:35 UTC, emeryro commented on src/website/src/pages/ec/components/message/docs/usage.mdx
> +  image="https://inno-ecl.s3.amazonaws.com/media/images/EC/Messages/Message2.jpg"
the image for mobile version is missing (even if it close, this is not the same)

2019-07-17 06:12 UTC, emeryro approved these changes

2019-07-17 06:12 UTC, merged