feat(footer-standardised): implement footer for standardised family - INNO-1819
ec-europa/europa-component-library pull request #1308
Opened 2019-09-26 12:57 UTC by yhuard

2019-09-26 13:14 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit f39f2be5edde4853d64fdc4d443264c2f97190a8

https://deploy-preview-1308--europa-component-library.netlify.com

2019-09-26 13:25 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 0b3c32e49aea66678697206209bcee4cde311c8c

https://deploy-preview-1308--europa-component-library.netlify.com

2019-09-27 06:46 UTC, emeryro requested changes

2019-09-27 06:46 UTC, emeryro commented on src/systems/ec/ec-component/ec-component-footer-standardised/ec-component-footer-standardised.twig
> +        <p class="ecl-footer-standardised__description ecl-u-mt-l">
spacing is different here on mobile

2019-09-27 07:27 UTC, emeryro approved these changes

2019-09-27 07:27 UTC, merged