fix(links): change link with icon display - INNO-1829
ec-europa/europa-component-library pull request #1320
Opened 2019-10-03 13:40 UTC by yhuard

Please double check there's no side effects

2019-10-03 13:51 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit df32d7ef9e512a6cbe332198d595bb4585087fde

https://deploy-preview-1320--europa-component-library.netlify.com

2019-10-04 06:10 UTC, emeryro requested changes
Display of links on several lines is indeed better:
before
![image](https://user-images.githubusercontent.com/25579221/66184731-64536c00-e67d-11e9-824d-f7cfa8196bb6.png)

after
![image](https://user-images.githubusercontent.com/25579221/66184740-6a494d00-e67d-11e9-84da-dc725958157f.png)

However, this has some side effect in several locations. Some of them are minor but still noticable (file download, footer, language list)
![image](https://user-images.githubusercontent.com/25579221/66184864-bdbb9b00-e67d-11e9-9d7f-b49642928b12.png)

But in some cases it is breaking (before on left):
social media follow
![image](https://user-images.githubusercontent.com/25579221/66184804-9b298200-e67d-11e9-9254-23c98d252d0c.png)
social media share
![image](https://user-images.githubusercontent.com/25579221/66184823-a41a5380-e67d-11e9-90b9-2f0c1468905e.png)
event content types
![image](https://user-images.githubusercontent.com/25579221/66184878-c90ec680-e67d-11e9-858f-38995f460d0a.png)

So we could fix this at the component/template level, but there may be other broken cases on sites using ECL.

2019-10-04 09:31 UTC, emeryro approved these changes

2019-10-04 12:42 UTC, planctus commented
I have to say that in many of the components, the alignment of the icon is still questionable, i'd say that in some of the cases playing with that single pixel movement of the element doesn't really change the feeling that something is not in the right place, but i believe that in most of these situation the problem comes from the "wrong" proportions between text and icon (typically it happens with arrows, see breadcrumb or pagination).
Anyway, i tried to check all the components including a link implementation and i couldn't spot anything clearlt broken by this implementation.. ;)

2019-10-04 12:42 UTC, merged