feat(ecl-editor): add editor CSS rules
ec-europa/europa-component-library pull request #1360
Opened 2019-10-21 07:17 UTC by emeryro

# PR description

The first step here is to decide how we will handle the editor CSS.
Here is the RFC:

2019-10-21 07:29 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit a14206c1a024fa7c267cf9c1abb7483c0580f1db

https://deploy-preview-1360--europa-component-library.netlify.com

2019-11-04 10:12 UTC, yhuard commented
My 2¢:
- Mixed CSS rules: 👎 (will break our BEM conventions linting process)
- Editor preset, with duplicated rules 👍👍 
  - "It may be tricky for developpers to use this preset specifically when needed (to be analysed)": if the developper has a doubt, she can embed the stylesheet on all the pages. It means 1 extra network request but it's not that bad.
- Editor preset, with SASS mixins 😕 
  - another con: it makes the code much less readable...
  - also: it might be hard to handle cases where the markup is slightly different in a wysiwyg compared to the markup of the component we provide
- Separated package for editors 👍
  - IMHO it makes it easier to develop and maintain

2019-11-12 08:32 UTC, yhuard requested changes
now what would be nice is to create a dummy page in storybook where we can see it in action ;)

2019-11-12 08:32 UTC, yhuard commented on docs/decisions/003-editor.md
> +| Status        | proposed                     |
```suggestion
| Status        | accepted                     |
```

2019-11-12 08:32 UTC, yhuard commented on docs/decisions/003-editor.md
> +```
```suggestion
```scss
```

2019-11-12 08:32 UTC, yhuard commented on docs/decisions/003-editor.md
> +```
```suggestion
```scss
```

2019-11-12 08:32 UTC, yhuard commented on docs/decisions/003-editor.md
> +```
```suggestion
```scss
```

2019-11-12 08:32 UTC, yhuard commented on docs/decisions/003-editor.md
> +```
```suggestion
```scss
```

2019-11-12 08:32 UTC, yhuard commented on docs/decisions/003-editor.md
> +```
```suggestion
```scss
```

2019-11-12 08:32 UTC, yhuard commented on docs/decisions/003-editor.md
> +```
```suggestion
```scss
```

2019-11-15 05:45 UTC, emeryro commented
playground added: https://5dce12d52570804233ab3ecb--europa-component-library.netlify.com/playground/ec/?path=/story/utilities-editor--sample

2019-11-15 08:43 UTC, yhuard requested changes
- The table looks weird on small viewports (because of the missing data attributes) ; please align with Antonio regarding this issue
- The paragraphs and headings are sensitive to colour changes (`#test-fake-global-rules`)

2019-11-18 01:56 UTC, emeryro commented
- for tables, I added a comment on the ticket
- for text color, yes that's how the paragraphs and headings are defined. That's the same for non ecl-editor ones. Enforcing the color here may cause issues (what if the content has to be written in white forinstance?)

2019-11-18 10:40 UTC, yhuard approved these changes
good enough for now, we'll tackle the existing issues later

2019-11-18 10:40 UTC, merged