fix(site-header): add aria - INNO-1900
ec-europa/europa-component-library pull request #1380
Opened 2019-10-28 02:06 UTC by emeryro

# PR description

Add missing aria attributes

2019-10-28 02:20 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit e62f58fc8fb56c604e7815d5a8a5ea8f7f9193dd

https://deploy-preview-1380--europa-component-library.netlify.com

2019-10-28 08:32 UTC, yhuard requested changes

2019-10-28 08:32 UTC, yhuard commented on src/systems/ec/implementations/react/components/site-header-core/src/SiteHeaderCore.jsx
> +                aria-controls="language-list-overlay"
2 things:
- add the aria attributes only if `languageSelector && languageSelector.overlay` is true
- provide a default value for `aria-epxanded` (`aria-epxanded="false"`)

To go further: add [`aria-modal="true"`](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html) on `LanguageListOverlay` when the modal is open. When it's not open, remove the attribute ([better than `aria-modal="false"`](https://developer.paciellogroup.com/blog/2018/06/the-current-state-of-modal-dialog-accessibility/))

2019-10-29 20:24 UTC, yhuard approved these changes

2019-10-29 20:33 UTC, merged