docs(gallery-overlay): Adding content - INNO-2035
ec-europa/europa-component-library pull request #1477
Opened 2019-12-20 16:23 UTC by papegaill

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)
- [ ] The redirects in `src/website/src/routes/Redirects.jsx` are up-to-date

2019-12-20 16:25 UTC, papegaill reviewed
@kalinchernev Do you know how to order sub-items in the menu? ideally _Gallery-overlay_ should come after _Gallery_

2019-12-23 09:28 UTC, kalinchernev commented
Hi @papegaill the organisation of the navigation is based on the file system organisation of folders and files. Giving the existing system a try on this though didn't produce a good result:

![Gallery - Media - ECL v2](https://user-images.githubusercontent.com/1923476/71349124-dd74a800-2576-11ea-8c76-40755cea061c.png)

Making the Gallery a group doesn't help too. We can't nest a component inside another component in the existing logic of `src/website/src/components/Navigation/LinkList.jsx` without having this broken styling.

In order to keep it simple though, I'd suggest making it like this: #1490

In reality, the gallery overlay is not a separate component but a behavior of the gallery itself. That's why in my opinion this is acceptable representation:

![Screenshot_20191223_111923](https://user-images.githubusercontent.com/1923476/71349238-36dcd700-2577-11ea-88d2-3ef1b7d6e69d.png)

It would make more sense in this way  IMO because it doesn't introduce the unnecessary duplication and still provides the necessary URL structure and documentation usage guidelines.

2019-12-23 10:52 UTC, kalinchernev requested changes
Could you please combine the two usage sections into 1 as discussed in slack please?

2019-12-23 11:34 UTC, kalinchernev approved these changes

2019-12-23 11:34 UTC, merged