fix(EU): add missing elements - FRONT-1190
ec-europa/europa-component-library pull request #1600
Opened 2020-06-08 09:11 UTC by emeryro

# PR description

Add missing elements in ECL EU:
- eu-component-fact-figures
- eu-component-form-datepicker
- eu-component-label
- eu-component-menu
- eu-editor
- eu-preset-editor
- eu-utility-dimension
- eu-utility-print

2020-06-09 12:26 UTC, planctus commented
In the ecl editor in storybook:
![image](https://user-images.githubusercontent.com/14326885/84147145-32d93e80-aa5d-11ea-89eb-6ba98a698c7b.png)

2020-06-09 12:50 UTC, planctus commented
in the print if i click on the css resources i don't see the same as in EC, meaning that the font size gets reduced there and not here, not sure it is supposed to be exactly the same, though.
![print](https://user-images.githubusercontent.com/14326885/84149344-9e70db00-aa60-11ea-84fb-3677bca072cf.gif)

2020-06-09 13:00 UTC, planctus commented
Not sure this is a problem either, but the order of the components in storybook is somehow "manually" handled in ECL? Yo usee the new components they are at the bottom, here:
![image](https://user-images.githubusercontent.com/14326885/84150183-cdd41780-aa61-11ea-9ac0-f51a335ca574.png)

2020-06-09 13:10 UTC, planctus commented
Are we sure it was a good idea to include the menu in the list of component we could clone as they are in EC?
I mean, it looks really EC, it has the blue background and it contains the site name in the demo due to the "madness" of the family headers that we still don't have in EU, i would maybe consider to include this in the list of things for which we expect some "specs", what do you think?

2020-06-09 14:04 UTC, planctus commented
the dist is failing, not sure how this is related to these changes:

![image](https://user-images.githubusercontent.com/14326885/84157282-daa93900-aa6a-11ea-8fb3-3bf69bd6893d.png)

2020-06-09 14:14 UTC, planctus requested changes

2020-06-09 14:14 UTC, planctus commented on src/systems/eu/implementations/vanilla/packages/eu-component-fact-figures/package.json
> +  "style": "ec-component-fact-figures.scss",
These two are still "ec"

2020-06-09 14:25 UTC, planctus commented
Ah, i haven't noticed caused the website started, but i had errors while running start:website, it's a repeated one in all the components:
![image](https://user-images.githubusercontent.com/14326885/84159838-d3375f00-aa6d-11ea-85d0-b565db558393.png)

2020-06-10 07:07 UTC, emeryro commented
thanks for the review @planctus 

- eu-editor has been fixed (preset was not loaded correctly)
- print differences may come from css differences in existing components. It will be handled in https://citnet.tech.ec.europa.eu/CITnet/jira/browse/FRONT-1204
- order of elements in storybook is due to the use of mixed syntax for stories. All stories in EU will be updated in https://citnet.tech.ec.europa.eu/CITnet/jira/browse/FRONT-1205 so things should be fine
- for the menu, that's a fair point, it could be discussed with COMM. But anyways, we needed to have the component so if we have to change a color that would be quick, and probably done in https://citnet.tech.ec.europa.eu/CITnet/jira/browse/FRONT-1203
- I can't reproduce the errors you have with the build (and drone seems to work fine too). It doesn't seems to be related to this task (lots of ec stuff). If that still happens we could investigate in another ticket

2020-06-10 08:10 UTC, planctus commented
This is not anything you set in this pr, i think, but in this file:
src/systems/eu/implementations/vanilla/packages/eu-auto-init/index.js
we `import { queryAll } from '@ecl/ec-base/helpers/dom';`

2020-06-10 08:19 UTC, emeryro commented
I didn't check existing components yet, that will be handled in citnet.tech.ec.europa.eu/CITnet/jira/browse/FRONT-1204
But sure, that will be fixed with a full diff between components

2020-06-10 08:21 UTC, planctus approved these changes

2020-06-10 09:00 UTC, merged