feat(message): migrate component message - FRONT-1767
ec-europa/europa-component-library pull request #1748
Opened 2020-11-11 09:12 UTC by emeryro

# PR description

migrate component message to new structure

2020-11-11 15:03 UTC, planctus requested changes
very minor changes.. :)

2020-11-11 15:03 UTC, planctus commented on src/implementations/twig/components/message/README.md
> +- **"_compliance_"** (optional) (boolean) (default: false) Activates debug
```suggestion
- **"\_compliance\_"** (optional) (boolean) (default: false) Activates debug
```

2020-11-11 15:03 UTC, planctus commented on src/implementations/twig/components/message/README.md
> +- **"_compliance_inner_check_"** (optional) (boolean) (default: false) Inline compliance report
```suggestion
- **"\_compliance_inner_check\_"** (optional) (boolean) (default: false) Inline compliance report
```

2020-11-11 15:03 UTC, planctus commented on src/implementations/vanilla/components/message/README.md
> +# Message
I've never fully understood the reason why, but we write this in "plural".. :)
```suggestion
# Messages
```

2020-11-11 15:03 UTC, planctus commented on src/implementations/vanilla/components/message/message-print.scss
> +$_boder-width: 0.5mm;
border, no..? :)

2020-11-11 15:03 UTC, planctus commented on src/implementations/vanilla/components/message/package.json
> +    "@ecl/dom-utils": "^3.0.0",
I noticed that i forgot to add this dependency in the vanilla package of the file, would you add it in this pr..?

2020-11-11 15:03 UTC, planctus commented on src/website/src/pages/ec/components/message/docs/usage.mdx
> +import { Paragraph, Anatomy, Do, Caution } from '@ecl/website-components';
Do we need this Do and Caution..?

2020-11-12 05:30 UTC, kalinchernev commented on src/implementations/vanilla/components/message/package.json
> +    "@ecl/dom-utils": "^3.0.0",
I've added all missing in #1744
Well-noticed for future packages depending on the queryOne

2020-11-12 05:31 UTC, kalinchernev commented on src/implementations/twig/components/message/README.md
> +- **"_compliance_inner_check_"** (optional) (boolean) (default: false) Inline compliance report
I notice these changing back and forth: what's the deal with this?

2020-11-12 08:12 UTC, emeryro commented on src/implementations/twig/components/message/README.md
> +- **"_compliance_inner_check_"** (optional) (boolean) (default: false) Inline compliance report
I guess that the "correct name" of the parameter is `_compliance_inner_check_` (with extra underscores), but in markdown it is interpreted as italic if we don't escape it

2020-11-12 09:14 UTC, merged