feat(pagination): Adding component - FRONT-1781
ec-europa/europa-component-library pull request #1759
Opened 2020-11-13 16:42 UTC by papegaill

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)
- [ ] The redirects in `src/website/src/routes/Redirects.jsx` are up-to-date

2020-11-16 07:19 UTC, emeryro requested changes
Almost good, just a few points below

2020-11-16 07:19 UTC, emeryro commented on src/website/src/pages/ec/components/navigation/pagination/docs/code.mdx
> +  selectedKind="components-pagination"
```suggestion
  selectedKind="components-navigation-pagination"
```

2020-11-16 07:19 UTC, emeryro commented on src/implementations/twig/components/pagination/pagination.test.js
> +describe('EC - Pagination', () => {
```suggestion
describe('Pagination', () => {
```

2020-11-16 07:19 UTC, emeryro commented on src/implementations/vanilla/components/pagination/package.json
> +  "sass": "button.scss",
bad copy paste I guess

2020-11-16 07:19 UTC, emeryro commented on src/specs/components/pagination/package.json
> +  "description": "ECL EC Pagination Specs",
```suggestion
  "description": "ECL Pagination Specs",
```

2020-11-17 13:11 UTC, emeryro commented
@papegaill the tests have to be updated here

2020-11-18 16:24 UTC, planctus commented
in the website, we miss the arrows of the previous and next link: 
https://ecl-preview-1759--europa-component-library.netlify.app/ec/components/navigation/pagination/code/

![image](https://user-images.githubusercontent.com/14326885/99557379-48b73c00-29cb-11eb-9d12-6548607910a2.png)

2020-11-19 16:17 UTC, planctus approved these changes

2020-11-19 16:17 UTC, planctus commented on src/implementations/vanilla/components/pagination/package.json
> +  "sass": "button.scss",
```suggestion
  "sass": "pagination.scss",
```

2020-11-19 16:17 UTC, planctus commented on src/presets/dev/package.json
> +    "@ecl/vanilla-component-pagination": "^3.0.0",
Shouldn't come after page-banner? :)

2020-11-19 16:21 UTC, merged