feat(search-form): migrate component search form - FRONT-1775
ec-europa/europa-component-library pull request #1760
Opened 2020-11-16 12:42 UTC by emeryro

# PR description

migrate component search form to new structure

2020-11-17 13:34 UTC, planctus requested changes
Super small things, as usual.. :)

2020-11-17 13:34 UTC, planctus commented on src/implementations/twig/components/search-form/README.md
> +- **"\_compliance"** (boolean) (default: false) Activates debug
```suggestion
- **"\_compliance\_"** (boolean) (default: false) Activates debug
```

2020-11-17 13:34 UTC, planctus commented on src/implementations/twig/components/search-form/README.md
> +- **"_compliance_inner_check_"** (boolean) (default: false) Inline compliance report
```suggestion
- **"\_compliance_inner_check\_"** (boolean) (default: false) Inline compliance report
```

2020-11-17 13:34 UTC, planctus commented on src/implementations/twig/components/search-form/__snapshots__/search-form.test.js.snap
> +exports[`Search Form with validation enabled and missing input data returns the right warning message 1`] = `
Not sure it's worth checking this, but i don't see any output from the compliance tool here

2020-11-17 13:34 UTC, planctus commented on src/implementations/twig/components/search-form/README.md
> +- **"text_input"** (associative array) default: A predefined structure for EC Text Input
```suggestion
- **"text_input"** (associative array) default: Predefined structure for the text-Input component
```

2020-11-17 13:34 UTC, planctus commented on src/implementations/twig/components/search-form/README.md
> +- **"button"** (associative array) default: A predefined structure for EC Button
```suggestion
- **"button"** (associative array) default: Predefined structure for the Button component
```

2020-11-17 13:38 UTC, emeryro commented on src/implementations/twig/components/search-form/__snapshots__/search-form.test.js.snap
> +exports[`Search Form with validation enabled and missing input data returns the right warning message 1`] = `
honnestly, I didn't really check what test is run here.
As we don't know if we will keep the compliance tool as is in the end, I'd say that we can handle this at a later stage

2020-11-18 07:53 UTC, kalinchernev reviewed
Only 1 question from me on this one

2020-11-18 07:53 UTC, kalinchernev commented on src/implementations/twig/components/search-form/search-form.story.js
> +export const Default = () => searchForm(prepareSearchForm(dataDefault));
Strangely, https://ecl-preview-1760--europa-component-library.netlify.app/playground/ec/?path=/story/components-forms-search-form--default does not seem to look like https://ecl-twig-js.netlify.app/ec/?path=/story/components-forms-search-form--default 

The search label doesn't seem to show up

2020-11-20 07:34 UTC, kalinchernev approved these changes

2020-11-20 07:34 UTC, merged

2020-11-20 07:35 UTC, kalinchernev commented on src/implementations/twig/components/search-form/search-form.story.js
> +export const Default = () => searchForm(prepareSearchForm(dataDefault));
It was the difference in addons panel. So the panel of responsive was below the breakpoint to get the same style.
Bref, no issues.