feat(gallery): Adding component - front-1776
ec-europa/europa-component-library pull request #1762
Opened 2020-11-16 19:34 UTC by planctus

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)
- [ ] The redirects in `src/website/src/routes/Redirects.jsx` are up-to-date

2020-11-17 13:24 UTC, emeryro requested changes

2020-11-17 13:24 UTC, emeryro commented on src/implementations/twig/components/gallery/package.json
> +  "publishConfig": {
this should be removed, as the package is set to private

2020-11-17 13:24 UTC, emeryro commented on src/implementations/vanilla/components/gallery/gallery.scss
> +.ecl-gallery__slider-image-container, // DEPRECATED
the deprecated rule can probably be removed

2020-11-17 13:24 UTC, emeryro commented on src/implementations/vanilla/components/gallery/gallery.scss
> +@include breakpoints.up('md') {
```suggestion
@include breakpoints.up('m') {
```

2020-11-17 13:24 UTC, emeryro commented on src/implementations/vanilla/components/gallery/gallery.scss
> +  .ecl-gallery__slider-image-container, // DEPRECATED
same here

2020-11-18 09:15 UTC, kalinchernev commented
No issues after a check on my side. Only the need to update the branch to the latest version of next-v3.

2020-11-18 12:26 UTC, merged