feat(site-header-core): Adding component, FRONT-1798
ec-europa/europa-component-library pull request #1772
Opened 2020-11-23 12:49 UTC by planctus

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)
- [ ] The redirects in `src/website/src/routes/Redirects.jsx` are up-to-date

2020-11-24 07:16 UTC, emeryro requested changes
Component is fine, just the tests to be updated

2020-11-24 09:32 UTC, kalinchernev requested changes
Minor comments

2020-11-24 09:32 UTC, kalinchernev commented on src/implementations/vanilla/components/site-header-core/site-header-core-print.scss
> +  padding-top: map.get(spacing.$spacing-print, '4xl');
In v2, these are

```scss
    padding-bottom: $ecl-spacing-print-xl;
    padding-top: $ecl-spacing-print-xl;
```

2020-11-24 09:32 UTC, kalinchernev commented on src/implementations/vanilla/components/site-header-core/site-header-core.scss
> +@include breakpoints.up(s) {
The rest of the implementations have strings as parameters. 
```
@include breakpoints.up('s')
```

2020-11-24 09:32 UTC, kalinchernev commented on src/implementations/vanilla/components/site-header-core/site-header-core.scss
> +@include breakpoints.up(l) {
Same comment for string input parameters here.

2020-11-25 10:38 UTC, kalinchernev approved these changes

2020-11-25 10:38 UTC, merged