feat(controls): Textarea, replacing knobs with controls - FRONT-1865
ec-europa/europa-component-library pull request #1845
Opened 2020-12-21 10:30 UTC by planctus

2020-12-21 11:10 UTC, papegaill requested changes

2020-12-21 11:10 UTC, papegaill commented on src/implementations/twig/components/text-area/text-area.story.js
> +    width: {
I added width control to the utils, see pending https://github.com/ec-europa/europa-component-library/pull/1842 or https://github.com/ec-europa/europa-component-library/pull/1844

2020-12-21 11:10 UTC, papegaill commented on src/implementations/twig/components/text-area/text-area.story.js
>  Default.decorators = [withKnobs, withNotes, withCode];
`withKnobs` can be remove as well as the import

2020-12-22 14:10 UTC, emeryro approved these changes

2020-12-22 14:10 UTC, merged