feat(page-header-standardised): Add controls - FRONT-1887
ec-europa/europa-component-library pull request #1867
Opened 2021-01-04 15:09 UTC by papegaill

2021-01-05 14:29 UTC, planctus submitted a review, later dismissed

2021-01-05 14:31 UTC, planctus commented on src/implementations/twig/components/page-header-standardised/page-header-standardised.story.js
> +  decorators: [withNotes, withCode],
We miss the parameters key to disable the knobs ;)

2021-01-05 14:32 UTC, planctus requested changes
Just the knobs tab to be disabled ;)

2021-01-07 08:08 UTC, emeryro approved these changes

2021-01-07 08:08 UTC, merged