feat(gallery): Adding EU styles, revamping EC - front-2255
ec-europa/europa-component-library pull request #2082
Opened 2021-05-26 15:06 UTC by planctus

2021-05-27 07:29 UTC, emeryro requested changes
A few little things

2021-05-27 07:29 UTC, emeryro commented on src/implementations/vanilla/components/gallery/_gallery.scss
> +[data-ecl-gallery-all] {
we should use a proper css class here instead of targeting the data-* attribute.
If there is none on the element, that's the good time to add one

2021-05-27 07:29 UTC, emeryro commented on src/implementations/vanilla/components/gallery/gallery-ec.scss
> +  $_description-icon-small: 1.5rem,
can't we use the icon sizes defined in the scss map?

2021-05-27 07:29 UTC, emeryro commented on src/implementations/vanilla/components/gallery/gallery-ec.scss
> +  $_icon-small: 1rem,
same here

2021-05-27 09:06 UTC, emeryro commented
Thanks for the update @planctus 
Can you just add a few lines in the migration doc for the most impacting updates in markup and data structure? (mostly the new class and the icon update)? Then we'll be good

2021-05-27 09:26 UTC, emeryro submitted a review, later dismissed

2021-05-28 09:32 UTC, papegaill reviewed
Is it normal: 
- that the overlay is not fully fullscreen, there is a space at the bottom EC and EU?
- to have the text in yellow on the close, next and previous buttons of the overlay in hover? same on EU for next/prev btns?
- to have a yellow focus border for gallery items in EU? it should follow the general blue focus right?

2021-05-28 09:42 UTC, planctus commented
For the first point yes, these styles were added in the implementation although missing in the specs, if you read the remarks in this pr designers were alerted about this and they approved those styles, they will update the specs basing on them.
For the other two point i think we need to fix those things, should be fairly easy, i will do it, wait before merging this, then.. ;)

2021-05-28 11:40 UTC, merged