feat(footers): Adding EC logo to all the footers - FRONT-3224
ec-europa/europa-component-library pull request #2222
Opened 2021-10-04 14:38 UTC by planctus

2021-10-08 12:50 UTC, papegaill requested changes

2021-10-08 12:50 UTC, papegaill commented on src/implementations/twig/components/footer-core/__snapshots__/footer-core.test.js.snap
> +            <a
Strange focus state actually on the logo:

<img width="628" alt="Screenshot 2021-10-08 at 14 33 40" src="https://user-images.githubusercontent.com/1289480/136557832-6f26f707-cf65-4203-b5a4-a9492c5fd52e.png">

already better by having `display:block` to the `href`

<img width="620" alt="Screenshot 2021-10-08 at 14 34 03" src="https://user-images.githubusercontent.com/1289480/136557951-b6ce6c34-e36a-46a4-9ad4-d8aad5e8d426.png">

I think it would be better to set the bottom margin on the parent `href` instead of the logo `img`so the focus will be better around the logo only. as made on standardised?

2021-10-08 12:50 UTC, papegaill commented on src/implementations/twig/components/footer-core/footer-core.story.js
>  export default {
Any control to show or hide the logo? 

Here is ticket description:
_"EU footers already have the logo. For EC, it must appear by default, but there should be an option to hide it."_

Same for standardised and harmonised, EU also?

2021-10-08 12:50 UTC, papegaill commented on src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
> +            <a
On the mocks it seems that for desktop they want first the heading "European Commission" then the logo. And reverse on mobile. maybe flex order? 

Same for harmonised.

2021-10-11 09:27 UTC, planctus commented on src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
> +            <a
are you looking on abstract..? The "mocks" have been updated after a request from us to align the behaviour of this section, the decision was to always have the logo on top, not sure the files have been updated also there, maybe it was done only on figma: https://www.figma.com/file/MZCXQtdJmpx8gzEvYlvwYn/EC-Components?node-id=170%3A3719

2021-10-11 09:28 UTC, planctus commented on src/implementations/twig/components/footer-core/footer-core.story.js
>  export default {
I've added a control to hide the logo in harmonised and standardised, not in core where no other "section" can be hidden.

2021-10-11 09:29 UTC, planctus commented on src/implementations/twig/components/footer-core/__snapshots__/footer-core.test.js.snap
> +            <a
You're right, the element was inline and that's why the margin was applied to the image, now this behaves as the others.

2021-10-11 10:36 UTC, papegaill commented on src/implementations/twig/components/footer-standardised/__snapshots__/footer-standardised.test.js.snap
> +            <a
yes looking on abstract ;)

2021-10-11 10:38 UTC, papegaill approved these changes

2021-10-11 14:59 UTC, merged