feat(radios): upgrade radios - INNO-631
ec-europa/europa-component-library pull request #223
Opened 2017-06-28 13:43 UTC by yhuard

TODO: fix the errors reported by axe-core:

```
- [critical] Ensures related <input type="radio"> elements have a group and that the group designation is consistent: -- [critical] #opt-1: --- [critical] All elements with the name "radio-example" do not reference the same element with aria-labelledby--- [critical] Element does not have a containing fieldset or ARIA group
```

2017-06-29 09:27 UTC, emeryro requested changes
A few modifications requested, but overall display is good

2017-06-29 09:27 UTC, emeryro commented on framework/components/ecl-forms/ecl-forms-radios/ecl-forms-radios.scss
> +  padding-left: 34px;
Magic number..
We should use same spacing as checkboxes.

2017-06-29 09:27 UTC, emeryro commented on framework/components/ecl-forms/ecl-forms-radios/ecl-forms-radios.twig
> +<div role="radiogroup" aria-labelledby="{{ id }}_label" id="{{ id }}">
Missing extraClass and extraAttributes

2017-06-29 09:27 UTC, emeryro commented on framework/components/ecl-forms/ecl-forms-radios/ecl-forms-radios.twig
>  </div>
I suggest to add disabled and error states too (as for other form elements)

2017-06-29 09:27 UTC, emeryro commented on framework/components/ecl-forms/ecl-forms-radios/ecl-forms-radios.scss
> +    transform: translateY(-50%);
I'm not a big fan of these "transform hack"..
In checkboxes component it has been done using line-height.

2017-06-29 09:30 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-radios/ecl-forms-radios.scss
> +  padding-left: 34px;
Totally agree!

2017-06-29 09:31 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-radios/ecl-forms-radios.scss
> +    transform: translateY(-50%);
And what happens when the label takes 2 lines? IMHO line-height is worse than transform

2017-06-29 09:31 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-radios/ecl-forms-radios.twig
>  </div>
Will do

2017-07-03 12:43 UTC, kalinchernev approved these changes

2017-07-03 13:30 UTC, emeryro approved these changes

2017-07-03 13:36 UTC, merged