feat(content-item): add component - FRONT-2499
ec-europa/europa-component-library pull request #2250
Opened 2021-11-03 14:17 UTC by emeryro

2021-12-08 10:36 UTC, papegaill requested changes

2021-12-08 10:36 UTC, papegaill commented on src/implementations/twig/components/content-item/content-item.html.twig
> +  <div class="ecl-content-item__taxonomy">
The div remains empty when you disable the taxonomies via the controls, maybe a if statement to avoid this?

2021-12-08 10:36 UTC, papegaill commented on src/implementations/twig/components/content-item/README.md
> +- **"card"** (associative array) (default: predefined structure below)
Seems the readme file is not updated with the new content-item parameters

2021-12-08 10:36 UTC, papegaill commented on src/implementations/twig/components/card/__snapshots__/card.test.js.snap
> +        META1 | Meta2
Normal to change, this at card level?

2021-12-08 10:36 UTC, papegaill commented on src/implementations/twig/components/content-item/README.md
> +  card: {
card include tag also needs to be updated

2021-12-08 10:36 UTC, papegaill commented on src/implementations/vanilla/components/content-item/content-item-print.scss
> +
the date block on the print event variant is broken

2021-12-08 10:36 UTC, papegaill commented on src/website/src/pages/ec/components/content-item/docs/usage.md
> +---
page needs to be added to the cms > src/website/public/admin/config.yml

2021-12-08 10:36 UTC, papegaill commented on src/website/src/pages/eu/components/content-item/docs/usage.md
> +title: Usage
page needs to be added to the cms > src/website/public/admin/config.yml

2021-12-08 10:36 UTC, papegaill commented on src/implementations/twig/components/content-item/package.json
> +    "@ecl/twig-component-date-block": "^3.1.2"
description-list ?

2021-12-09 07:47 UTC, emeryro commented on src/implementations/twig/components/card/__snapshots__/card.test.js.snap
> +        META1 | Meta2
yes, the content item is using the card as-is, and in both cases the first meta is supposed to be uppercase

2021-12-09 10:20 UTC, papegaill requested changes

2021-12-09 10:20 UTC, papegaill commented on src/implementations/twig/components/content-item/content-item.html.twig
> +  {% endif %}
`endif` should be after the ending `</div>`

2021-12-09 10:22 UTC, papegaill commented on src/implementations/vanilla/components/content-item/content-item-print.scss
> +
some spacing remain missing for the date block..
<img width="306" alt="Screenshot 2021-12-09 at 11 16 05" src="https://user-images.githubusercontent.com/1289480/145378456-532ad783-cbe1-4c17-b898-3cec6b2df38b.png">

2021-12-09 10:23 UTC, papegaill commented on src/implementations/twig/components/content-item/package.json
> +    "@ecl/twig-component-date-block": "^3.1.2"
also, everything needs to be updated to latest version 3.1.3

2021-12-09 14:55 UTC, merged