feat(category-filter): Add component - FRONT-3531
ec-europa/europa-component-library pull request #2323
Opened 2022-01-27 12:33 UTC by papegaill

2022-02-01 08:12 UTC, emeryro requested changes
nicely done.
The website page are still to be added

2022-02-01 08:12 UTC, emeryro commented on src/implementations/twig/components/category-filter/README.md
> +- **"items"** (associative array) (default: {}): The menu items - format:
parameter list does not seems up to date: reference to menu (also in the twig parameters list), and unused parameter "is_children"

2022-02-01 08:12 UTC, emeryro commented on src/implementations/twig/components/category-filter/category-filter-items.html.twig
> +{% set _level = level|default(1) %}
it is called "first_level" in the parameter list

2022-02-01 08:12 UTC, emeryro commented on src/implementations/twig/components/category-filter/category-filter.html.twig
> +<div
we may use ``<nav>`` instead of ``<div>``

2022-02-01 08:12 UTC, emeryro commented on src/implementations/twig/components/category-filter/package.json
> +  "description": "ECL Menu",
```suggestion
  "description": "ECL Category Filter",
```

2022-02-01 08:12 UTC, emeryro commented on src/implementations/twig/components/category-filter/package.json
> +  "version": "3.2.0",
version should be 3.2.2 for all packages

2022-02-01 08:12 UTC, emeryro commented on src/implementations/vanilla/components/category-filter/_category-filter.scss
> + * @define category-filter; weak
I guess that it it not a weak definition here

2022-02-01 08:12 UTC, emeryro commented on src/implementations/vanilla/components/category-filter/category-filter-print.scss
> +}
print version is quite basic.
we could improve it a little (use correct font, maybe remove the icons, ...)

2022-02-01 08:12 UTC, emeryro commented on src/implementations/vanilla/components/category-filter/category-filter-print.scss
> + * Menu component
to be updated

2022-02-01 08:12 UTC, emeryro commented on src/implementations/vanilla/components/category-filter/_category-filter.scss
> +}
we could display the items when no js is used, similar to what is done on expandable (https://github.com/ec-europa/europa-component-library/blob/v3-dev/src/implementations/vanilla/components/expandable/_expandable.scss#L24)

2022-02-01 08:12 UTC, emeryro commented on src/implementations/vanilla/components/category-filter/package.json
> +  "version": "3.2.0",
3.2.2

2022-02-01 08:12 UTC, emeryro commented on src/specs/components/category-fiter/package.json
> +  "version": "3.2.0",
3.2.2

2022-02-01 15:54 UTC, papegaill commented
thank you @emeryro  for the feedback that I applied, there are still the illustrations for the documentation pages that I am waiting for.

2022-02-03 13:58 UTC, emeryro approved these changes

2022-02-08 08:16 UTC, merged