feat(breadcrumb): add site-wide components - FRONT-3552
ec-europa/europa-component-library pull request #2347
Opened 2022-02-21 16:55 UTC by papegaill

2022-05-05 12:52 UTC, emeryro requested changes
There is something wrong with the website structure now, with two entries for the breadcrumb
![image](https://user-images.githubusercontent.com/25579221/166923886-765d2a64-6897-4441-b131-cd5506432be2.png)
To be checked with COMM (this does not block the PR)

2022-05-05 12:52 UTC, emeryro commented on src/implementations/twig/components/breadcrumb/breadcrumb.story.js
> +Standardised.storyName = 'standardised';
there is no page header standardised for EU, so I guess that it is the same for breadcrumb

2022-05-05 12:52 UTC, emeryro commented on src/implementations/twig/components/breadcrumb/package.json
> +  "version": "3.2.3",
version should be 3.2.4 everywhere

2022-05-05 12:52 UTC, emeryro commented on src/implementations/twig/components/breadcrumb/breadcrumb.html.twig
> +{% if _variant is not empty and _variant == 'negative' %}
do we really need to test if the variant is "negative"? we could just append to the class name, that's what is done in most components

2022-05-05 12:52 UTC, emeryro commented on src/implementations/vanilla/components/breadcrumb/breadcrumb-print.scss
> +.ecl-breadcrumb-standardised {
wrong copy/paste I guess, this should not be standardised here

2022-05-05 12:52 UTC, emeryro commented on src/website/src/pages/ec/components/site-wide/navigation/breadcrumb/docs/api.mdx
> +import BreadcrumbJSDoc from '../../../../../_jsdoc/breadcrumbcore.md';
should not be breadcrumb core I guess

2022-05-05 13:49 UTC, papegaill commented
> There is something wrong with the website structure now, with two entries for the breadcrumb ![image](https://user-images.githubusercontent.com/25579221/166923886-765d2a64-6897-4441-b131-cd5506432be2.png) To be checked with COMM (this does not block the PR)

Indeed, for now, I have removed the navigation folder under site-wide, I think it will  avoid confusion.

2022-05-10 05:50 UTC, emeryro requested changes
The standardised example should be removed from the website (EU)
![image](https://user-images.githubusercontent.com/25579221/167557330-e77033f8-4c07-4dab-b572-de072c36beef.png)

2022-05-10 10:41 UTC, emeryro approved these changes

2022-05-10 10:42 UTC, merged