feat(right-to-left): batch 5 - FRONT-3569
ec-europa/europa-component-library pull request #2382
Opened 2022-04-01 11:54 UTC by tibi2303

2022-04-12 13:33 UTC, papegaill submitted a review, later dismissed
Added rtl support also for other existing variants of the site-header, breadcrumb, page-header and footer:

- https://github.com/ec-europa/europa-component-library/pull/2382/commits/ab2b53901ce79ba46607e82a839423ac7752839b
- https://github.com/ec-europa/europa-component-library/pull/2382/commits/7a491356a55e9b3efa1c3cbd3dea118334b4d6a6

New pending site-wide breadcrumb and page-header also updated accordingly:

- https://github.com/ec-europa/europa-component-library/pull/2347/commits/9db426efae19dd94aacc71784658e86fcb84729d
- https://github.com/ec-europa/europa-component-library/pull/2337/commits/045aae0bec622b5ea8324fb42794ef8bea5863b7

2022-04-12 13:48 UTC, papegaill approved these changes, later dismissed

2022-04-25 12:58 UTC, emeryro requested changes
Meta are mixed up in the page header.
![image](https://user-images.githubusercontent.com/25579221/165093485-be5027e8-cbb6-437d-a3a6-5dee0afbaf4b.png)
I fixed some similar issues before, by addind white-space: pre-wrap on the container, and display: inline-block on the meta items

2022-04-25 13:52 UTC, papegaill commented
Fix metas for RTL added also for site-wide component: https://github.com/ec-europa/europa-component-library/pull/2337/commits/ee5600c1b006eb45adc3c6e85357539d6b385be0

2022-04-26 05:43 UTC, emeryro approved these changes

2022-04-26 05:43 UTC, merged