feat(ext-links): Adding external icon to links based on a parameter -  FRONT-3601
ec-europa/europa-component-library pull request #2384
Opened 2022-04-05 13:13 UTC by planctus

…

2022-04-12 06:57 UTC, emeryro requested changes

2022-04-12 06:57 UTC, emeryro commented on src/specs/components/card/demo/data--card.js
> +      external: true,
for the demo to COMM we can have the external link by default, but I guess that on the end we should have the normal link here (and maybe a control to have it external)

2022-04-12 06:57 UTC, emeryro commented on src/specs/components/content-item/demo/data--image.js
> +    external: true,
same remark for the default external link

2022-04-12 06:57 UTC, emeryro commented on src/specs/components/menu/demo/data--en.js
> +      external: true,
we should update the translated data file too

2022-04-13 07:35 UTC, planctus commented
Thanks for Romain for reviewing this, the examples were meant to show where the "functionality" was added to give a chance both to comm and platform to see what the result would have been. I agree that if this gets "validated" by our stakeholders we can simply remove the icon in some of the stories where we are currently showing it, i would also keep the control to activate it only for the link stories.

2022-04-20 14:00 UTC, planctus commented
It still not entirely clear how are we going to release this, the pr has been kept against v3, the examples have been removed, the link is the main "entry" point to test the "external icon" using the associated control

2022-04-22 10:56 UTC, planctus commented
The external icon has been added also to the tag component, only when the tag is of type "link"

2022-04-26 09:37 UTC, emeryro approved these changes

2022-04-26 10:36 UTC, merged