feat(tests): add tests for styles elements - INNO-649
ec-europa/europa-component-library pull request #243
Opened 2017-07-06 09:44 UTC by emeryro

Add visual regression tests.
Also put test files in folders, for easier maintenance.

2017-07-06 14:45 UTC, kalinchernev requested changes
CI gives error:
```
ERROR: Cannot find module '../../framework/components/ecl-buttons/variants.json'
```

Some tests can be combined and the variants can be fetched from the components definitions.

Thanks for adding tests! :)

2017-07-06 14:45 UTC, kalinchernev commented on test/functional/styles/colors.js
> -        name: 'colors',
Can we name the folder `content` to match the structure of the framework?

2017-07-06 14:45 UTC, kalinchernev commented on test/functional/styles/icons.js
> +const variants = [
let's `require` the `ecl-icons.config.js` directly and filter this so to avoid maintaining 2 definition sets?

2017-07-06 14:45 UTC, kalinchernev commented on test/functional/styles/icons.js
> +variants.forEach(variant => {
I think it'd be better to test `components/preview/ecl-icons` which has them all. That covers basically all modifiers and variants at the same time, 1 image per browser.

2017-07-06 14:45 UTC, kalinchernev commented on test/functional/styles/typography/headings.js
> +const variants = ['h1', 'h2', 'h3', 'h4', 'h5', 'headline'];
Could be useful to have it from `ecl-typography-headings.config.js` as well.

2017-07-06 14:45 UTC, kalinchernev commented on test/functional/styles/typography/lists.js
> +      browser.url(`ecl-typography-lists--${variant}.html`);
Why not have them in 1 page and screenshot as in the preview?

2017-07-06 14:45 UTC, kalinchernev commented on test/functional/styles/typography/paragraphs.js
> +const variants = ['l', 'm', 's', 'xs', 'xxs'];
Another potential candidate for a single test for all variants.

2017-07-10 12:50 UTC, emeryro commented on test/functional/styles/icons.js
> +variants.forEach(variant => {
Good point

2017-07-10 13:15 UTC, emeryro commented
Tests have been updated

2017-07-12 09:25 UTC, yhuard requested changes
Now that we have adopted the new folder structure for the tests, this PR has to be reworked ;)

2017-07-17 13:42 UTC, yhuard commented
Replaced by PR #289

2017-07-17 13:42 UTC, closed without merging