feat(z-index): add sass map and utilities - INNO-652
ec-europa/europa-component-library pull request #267
Opened 2017-07-11 08:45 UTC by emeryro

z-indexes are now defined in a sass variable, and used in components.
Current map of z-indexes can be updated if new needs are detected.

Components already upgraded using z-index have been updated.

Note: could not run visual tests for now, I will add them later, but code review can already be done.

2017-07-11 13:57 UTC, yhuard commented on framework/components/ecl-dropdowns/ecl-dropdowns.scss
> +  z-index: map-get($ecl-z-index, 'auto');
Why don't you use the `dropdown` index?

2017-07-11 13:57 UTC, yhuard commented on framework/components/ecl-datepickers/_datepickers.scss
> +  z-index: map-get($ecl-z-index, 'modal');
Isn't the datepicker more like a dropdown?

2017-07-12 06:00 UTC, emeryro commented on framework/components/ecl-dropdowns/ecl-dropdowns.scss
> +  z-index: map-get($ecl-z-index, 'auto');
Yes, my bad

2017-07-12 06:05 UTC, emeryro commented on framework/components/ecl-datepickers/_datepickers.scss
> +  z-index: map-get($ecl-z-index, 'modal');
To me it is more like a popup (= modal).
It has to be on top of other elements (including dropdowns)

2017-07-12 06:06 UTC, yhuard approved these changes

2017-07-12 06:07 UTC, yhuard requested changes
Just waiting for the small fix we discussed

2017-07-12 06:17 UTC, emeryro commented
Done

2017-07-12 06:47 UTC, yhuard approved these changes

2017-07-12 06:50 UTC, yhuard commented
We have to figure out why GH doesn't run the tests nor updates the statuses of the checks...

2017-07-12 06:50 UTC, merged