feat(site-header): Using picture, keeping data structure unchanged - FRONT-3882
ec-europa/europa-component-library pull request #2810
Opened 2023-03-23 08:50 UTC by planctus

2023-03-23 12:08 UTC, emeryro reviewed
Coulnd't we take advantage of the picture sources to group the mobile and desktop logo in the same tag?

2023-03-23 12:33 UTC, planctus commented
Fascinating, i did this on my own and then i read your comment.. :)

2023-03-28 05:54 UTC, emeryro requested changes

2023-03-28 05:54 UTC, emeryro commented on src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
> +              <source
this second source is not needed. By default it will take the image in the img tag (mobile) and switch to desktop

2023-03-28 05:54 UTC, emeryro commented on src/implementations/vanilla/components/site-header/site-header-eu.scss
> -.ecl-site-header__logo-image-mobile {
if we remove the previous css class definition, that would be a breaking change
So we should either keep them (deprecated) or flag the pr as breaking

2023-03-28 09:37 UTC, emeryro approved these changes

2023-03-28 09:38 UTC, merged