feat(card): Using picture - FRONT-3874
ec-europa/europa-component-library pull request #2817
Opened 2023-03-29 11:59 UTC by planctus

2023-03-30 11:17 UTC, emeryro requested changes

2023-03-30 11:17 UTC, emeryro commented on src/implementations/twig/components/card/__snapshots__/card.test.js.snap
we should add the usual test with previous data structure

2023-03-30 11:29 UTC, planctus commented on src/implementations/twig/components/card/__snapshots__/card.test.js.snap
we have that already, @emeryro 
```
  describe('Backward compatibility', () => {
    test('renders correctly with deprecated data', () => {
      expect.assertions(1);
      return expect(render(dataCardBc)).resolves.toMatchSnapshot();
    });
  });
```

2023-04-03 05:49 UTC, emeryro approved these changes

2023-04-03 05:50 UTC, merged