feat(button): improve display of button with icon only - FRONT-3976
ec-europa/europa-component-library pull request #2888
Opened 2023-06-01 08:41 UTC by emeryro

add new variant .ecl-button--icon-only to display square button with only the icon

2023-06-05 08:38 UTC, planctus approved these changes
Nice the removal of the before/after classes!

2023-06-14 07:19 UTC, planctus commented on docs/Migrating-v4.md
> +- New variant added to handle button with icon only: `ecl-button--icon-only`. By using it, it is no longer needed to add utility classes on the button label. If you are using the twig template, this
```suggestion
- New variant added to handle button with icon only: `ecl-button--icon-only`. By using it, it is no longer needed to add utility classes on the button label. If you are using the twig template, this variant relies on the already existing parameter `hide-label`
```

2023-06-14 07:58 UTC, planctus requested changes
Just a question about the template and a few others about the docs. We can improve the link to playground to demo the icon only use case.

2023-06-14 07:58 UTC, planctus commented on src/website/src/pages/ec/components/button/docs/code.mdx
> +Button label can be hidden by adding class `ecl-u-sr-only` to it. The label has to be filled in any case, to provide context to screen readers.
Isn't this information outdated?

2023-06-14 07:58 UTC, planctus commented on src/website/src/pages/ec/components/button/docs/code.mdx
> +Spacing of icon only button is adapted to make it square, but to have it work correctly, icon should be placed after the label.
Is this true? I've tried appending the label to the button, so after the icon and it still shows correctly

2023-06-14 07:58 UTC, planctus commented on src/website/src/pages/eu/components/button/docs/code.mdx
> +Button label can be hidden by adding class `ecl-u-sr-only` to it. The label has to be filled in any case, to provide context to screen readers.
Same question about the EC page..

2023-06-14 07:58 UTC, planctus commented on src/website/src/pages/eu/components/button/docs/code.mdx
> +  selectedStory="secondary"
shouldn't we add:
selectedArgs="icon_name:logged-in;hide_label:!true" to demo the icon only use case?

2023-06-14 07:58 UTC, planctus commented on src/implementations/twig/components/button/button.html.twig
> +{% if _hide_label %}
It feels it's a bit unsafe what we are doing, i mean that you specify in the docs that the icon has to be present for the hide_label param to work properly, but to me we should kind of ignore it, then, in case there is no icon, because otherwise you get the square layout and the label still visible, and we could prevent this from happening

2023-06-14 07:58 UTC, planctus commented on src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
>                    <button
Probably this is not relevant, the language toggle is a link, not a button, but it looks like this currently:
![image](https://github.com/ec-europa/europa-component-library/assets/14326885/df0fa97a-88b4-4032-b118-ef51a4b6c76c)
In Eu:
![image](https://github.com/ec-europa/europa-component-library/assets/14326885/fa325cb5-2550-46e3-9b40-36e382147df5)

I do have concerns regarding this color palette for EC, by the way, how can this blue be the primary color? Everything looks like it's disabled and the "disabled" becomes almost unreadable.

2023-06-14 08:00 UTC, planctus commented
I removed the markup changes label from the pr, this is for ECL 4, right..? I feel that we might have too many prs involving markup changes for this label to be relevant, and it's a major version, anyhow,

2023-06-14 09:33 UTC, emeryro commented on src/website/src/pages/eu/components/button/docs/code.mdx
> +  selectedStory="secondary"
unfortunately, passing arguments set in a select list in storybook do not work (at least I never found a way to make it work).
So we could pass the boolean to hide the label indeed, but not the icon name

2023-06-14 09:44 UTC, emeryro commented on src/implementations/twig/components/site-header/__snapshots__/site-header.test.js.snap
>                    <button
I noticed it too. 
The ticket for the language switcher is ready, so we'll handle that in it.

And for the primary color, that's how the designer defined it... It doesn't look so bad on my side, maybe it's related to your screen

2023-06-14 10:54 UTC, planctus approved these changes

2023-06-14 12:57 UTC, merged