fix(labels): refactor labels templates - INNO-703
ec-europa/europa-component-library pull request #290
Opened 2017-07-17 13:27 UTC by yhuard

# PR description

Refactor the templates of labels and radios as an example. You can either pass `label` property or block to the new template 💪 

# QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] the template is fully functional
- [ ] I have filled the README.md file (at least a few lines)
- [ ] I have checked the dependencies
- [ ] there are no hardcoded strings (all content come from the context)

2017-07-17 14:41 UTC, kalinchernev requested changes
You have missed 1 variable convention :P

2017-07-17 14:41 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-labels/ecl-forms-labels.twig
> +  {% set _cssClass = _cssClass ~ ' ' ~ extra_classes %}
Why not `_css_class`?

2017-07-17 14:42 UTC, kalinchernev commented
Honestly, I have a second thought of including a screenshot for the IE in Windows. It's obviously something not taken care of and does not have much value to have in regression tests.

2017-07-18 08:42 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-labels/ecl-forms-labels.twig
> +  {% set _cssClass = _cssClass ~ ' ' ~ extra_classes %}
My bad, I fix it

2017-07-18 08:46 UTC, kalinchernev submitted a review, later dismissed

2017-07-18 09:59 UTC, kalinchernev approved these changes

2017-07-18 09:59 UTC, merged