fix(checkboxes): fix checkboxes - INNO-704
ec-europa/europa-component-library pull request #295
Opened 2017-07-18 13:06 UTC by yhuard

# PR description

Fix checkboxes. Because checkboxes were broken.

# QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] the template is fully functional
- [ ] I have filled the README.md file (at least a few lines)
- [ ] I have checked the dependencies
- [ ] there are no hardcoded strings (all content come from the context)

2017-07-18 14:11 UTC, kalinchernev requested changes
Good improvements in overall. Only small comments.

2017-07-18 14:11 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-checkboxes/ecl-forms-checkboxes.twig
> +    <input class="ecl-checkbox__input ecl-sr-only" type="checkbox" id="{{ _id }}" value="{{ _value }}" name="{{ _name }}"{{ _checked ? ' checked' : '' }}{{ (_is_disabled is defined and _is_disabled =
`_value` can't have value here, as it never gets assigned as in the label.

2017-07-18 14:11 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-checkboxes/ecl-checkboxes.scss
> +  padding: map-get($ecl-spacing, 'xxxs') 0;
Quite a difference. I checked spec pages (even [old such](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Checkbox)) and didn't find any specific info about this, so I hope it's ok.

2017-07-19 07:01 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-checkboxes/ecl-checkboxes.scss
> +  font-size: 1rem;
Sure :)

2017-07-19 07:22 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-checkboxes/ecl-forms-checkboxes.twig
> +    <input class="ecl-checkbox__input ecl-sr-only" type="checkbox" id="{{ _id }}" value="{{ _value }}" name="{{ _name }}"{{ _checked ? ' checked' : '' }}{{ (_is_disabled is defined and _is_disabled =
In fact it does ;)

`{% embed '@ec-europa/ecl-forms-labels' with { 'for': id, 'extra_classes': _cssClass, 'extra_attributes': _extra_attributes, _id: id, _value: value, _name: name, _label: label, _checked: checked, _is_disabled: is_disabled } only %}` creates a local scope with only the variables declared here, include `_value`

2017-07-19 07:24 UTC, yhuard commented
PR updated with some fixes + one more example (checked by default) + value

2017-07-19 08:25 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-checkboxes/ecl-forms-checkboxes.twig
> +    <input class="ecl-checkbox__input ecl-sr-only" type="checkbox" id="{{ _id }}" value="{{ _value }}" name="{{ _name }}"{{ _checked ? ' checked' : '' }}{{ (_is_disabled is defined and _is_disabled =
Ok, I learned something new. Honestly, I still feel it's not very readable, but since it works, it's not a problem.

2017-07-19 08:26 UTC, kalinchernev approved these changes

2017-07-19 08:42 UTC, kalinchernev approved these changes

2017-07-19 08:42 UTC, merged