feat(dialog): add component - INNO-679
ec-europa/europa-component-library pull request #296
Opened 2017-07-18 13:16 UTC by kalinchernev

# PR description

Named dialog to be closer to the web specifications.
To test, please add `<a href="#dialog" class="ecl-link" data-ecl-dialog="ecl-dialog">Open dialog</a>` or similar trigger in the template to be able to run the code.

I feel this part can be better, I welcome suggestions whether should I rework a bit this from the other component. 
```
<button type="button" class="ecl-message__dismiss" aria-label="{{ dismiss.label }}">&times;</button>
``` 

I haven't included tests, as there is nothing visual without adding an actual trigger.

As this is a single-commit pull request, if you want to see history of commits, this is the [branch I will delete](https://github.com/ec-europa/europa-component-library/pull/294), but keep only for reference purpose.

# QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] the template is fully functional
- [ ] I have filled the README.md file (at least a few lines)
- [ ] I have checked the dependencies
- [ ] there are no hardcoded strings (all content come from the context)

2017-07-19 09:28 UTC, yhuard requested changes
A bit hard to test, maybe adding a new preview template could help. 

By the way, the focus is not captured when the modal is open (I can focus elements outside of the modal). Furthermore, I'd give the focus to the first focusable element inside the modal when you open it.

Maybe it's time to discuss INNO-626 ;)

2017-07-19 09:28 UTC, yhuard commented on framework/components/ecl-dialogs/ecl-dialogs.scss
> +  &[aria-hidden='true'],
Can't it be just:

```scss
  display: none;

  &[aria-hidden='false'] {
    display: block;
  }
```

2017-07-19 15:14 UTC, kalinchernev commented on framework/components/ecl-dialogs/ecl-dialogs.scss
> +  &[aria-hidden='true'],
I think it'd be even better to reuse the global reset approach. Thanks for pointing out a possible improvement!

2017-07-20 07:11 UTC, kalinchernev commented
Modifications applied.

2017-07-20 07:22 UTC, yhuard commented
I'll check

2017-07-20 07:59 UTC, yhuard requested changes

2017-07-20 07:59 UTC, yhuard commented on framework/components/ecl-dialogs/dialogs.js
>      queryAll(
Better:

```js
const dialogWindow = document.getElementById(dialogWindowId);
const focusableElements =  queryAll('a[href], ..........', dialogWindow);
```

2017-07-20 09:06 UTC, kalinchernev commented on framework/components/ecl-dialogs/dialogs.js
>      queryAll(
right, thanks!

2017-07-20 11:23 UTC, yhuard commented on framework/components/ecl-dialogs/dialogs.js
> +    dialogOverlay.addEventListener('click', () => {
May I ask why the change?

2017-07-20 12:09 UTC, kalinchernev commented on framework/components/ecl-dialogs/dialogs.js
> +    dialogOverlay.addEventListener('click', () => {
Just to make it shorter.

2017-07-20 12:26 UTC, yhuard commented on framework/components/ecl-dialogs/dialogs.js
> +    dialogOverlay.addEventListener('click', () => {
Sure! You can apply the same logic to line 129, just to be consistent ;)

2017-07-20 14:08 UTC, kalinchernev commented on framework/components/ecl-dialogs/dialogs.js
> +    dialogOverlay.addEventListener('click', () => {
Right ;D
PS Sorry I missed it

2017-07-21 06:54 UTC, yhuard approved these changes

2017-07-21 06:54 UTC, yhuard commented
Works like a charm!

2017-07-21 06:54 UTC, merged