feat(select): EC Revamp for V4 - FRONT-4106
ec-europa/europa-component-library pull request #3061
Opened 2023-10-13 11:31 UTC by planctus

2023-10-16 11:08 UTC, emeryro requested changes
There is an issue on the single select: when trying to open it with the mouse it immediately closes

Also the keyboard navigation ha changed for select multiple: before, the user put the focus on the select, and decided to open it or no, now it is open immediately when the focus is on it.
I think that this will be reported as an issue for accessibility (being forced to go through all the select options)

2023-10-16 11:08 UTC, emeryro commented on docs/Migrating-v4.md
> +- Both "variants" are now using javascript. For the single an multiple select a selector `ecl-select--active` is toggled in order to apply a transformation to the toggle icon.
```suggestion
- Both "variants" are now using javascript. For the single and multiple select a selector `ecl-select--active` is toggled in order to apply a transformation to the toggle icon.
```

2023-10-16 14:46 UTC, planctus commented
Was the issue you've found really about the single select..? There was a misbehaviour in the multiselect where two operations were executed in a sequence doing the opposite, this has been fixed.

There are some many listeners that it's easy to see them overlapping in certain cases, for the default select, though, we don't really do much, we basically handle the selector we use to style the icon, for the rest is pretty much the standard experience.

The fact that the multiselect dropdown was opening with a simple Tab was on purpose, at least this seemed the expected behaviour on the design side, but i reverted it and now it's just like it used to be, just that now we react to both Enter and Space, other behaviours related to the navigation with the keyboard have been adapted.

2023-10-17 06:48 UTC, emeryro commented
This is fine for the multi select
For the single select, I still have some unconsistent behaviour, mostly for the icon display
![2023-10-17-select](https://github.com/ec-europa/europa-component-library/assets/25579221/573e8545-54dc-4ecb-80c5-252ff4f84511)
Also when using the keyboard, the icon is flipped even if the dropdown is not open, but I guess that we cannot do much about that.

These are not blockers, but to be checked with the designers if we want to keep this approach

2023-10-17 08:23 UTC, planctus commented
Right, the behavior of the single select was initially implemented basing on the focus event, being the click not reliable enough, now i changed this into a combination of mousedown and click plus the keyboard so that we can have a consistent behaviour even when navigating with the keyboard:
you first focus on the select, then when you open it you get the flipping icon, when you close it the icon goes back to its original position.

2023-10-26 06:06 UTC, emeryro approved these changes

2023-10-26 06:06 UTC, merged