chore(controls): Adding conditions for toggable controls - FRONT-4118
ec-europa/europa-component-library pull request #3072
Opened 2023-10-19 10:56 UTC by planctus

2023-10-23 06:48 UTC, emeryro requested changes
That's a nice feature!
I just spotted a few cases where it could be improved

- banner: "label" is linked to the CTA button display
- featured item: "position" is only used if there is a picture
- site header: "EU languages" and "non-EU languages" can be hidden if there is no language switcher

2023-10-23 06:48 UTC, emeryro commented on src/playground/addons/story-utils/index.js
> +    if: { arg: 'invalid' },
that doesn't seem to work. Invalid text control is always displayed

2023-10-23 14:51 UTC, planctus commented on src/playground/addons/story-utils/index.js
> +    if: { arg: 'invalid' },
yep, tried a few different combinations, just using now "invalid" as a condition for both show_message and invalid_text, at least this works ;)

2023-10-24 08:02 UTC, emeryro approved these changes

2023-10-24 08:03 UTC, merged