feat(timelines): upgrade timelines - INNO-702
ec-europa/europa-component-library pull request #323
Opened 2017-07-25 13:48 UTC by yhuard

# PR description

Timeline component. Upgraded.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-07-26 10:09 UTC, emeryro requested changes
Overall display is good, a few changes to be done

2017-07-26 10:09 UTC, emeryro commented on framework/components/ecl-timelines/_timelines.scss
> +  &::before {
Bullets are a little too high; there are not aligned with the title (due to its line-height)

2017-07-26 10:09 UTC, emeryro commented on framework/components/ecl-timelines/ecl-timelines.config.js
> +          <p class="ecl-paragraph">
Shouldn't we use a block here instead?
As the content may be complex (with links and so), it would be cleaner.

2017-07-26 10:09 UTC, emeryro commented on framework/components/ecl-timelines/README.md
> +- **time schedule**
What about this variant? Isn't it part of the scope?

2017-07-26 12:08 UTC, yhuard commented on framework/components/ecl-timelines/ecl-timelines.config.js
> +          <p class="ecl-paragraph">
Sure, but how do you use a block in a `for` loop?

2017-07-26 12:09 UTC, yhuard commented on framework/components/ecl-timelines/README.md
> +- **time schedule**
I guess that either you use dates (like `By late-2013`) or times (`2pm`)  and that's they would call "time schedule"

2017-07-26 12:09 UTC, yhuard commented on framework/components/ecl-timelines/timelines.js
> +export default timelines;
Will check it, thanks for reporting

2017-07-26 13:00 UTC, yhuard commented on framework/components/ecl-timelines/timelines.js
> +export default timelines;
Note: this has been fixed on slack (internally) :)

2017-07-26 13:21 UTC, emeryro commented on framework/components/ecl-timelines/ecl-timelines.config.js
> +          <p class="ecl-paragraph">
Hmm.. good question...

2017-07-26 13:22 UTC, yhuard commented on framework/components/ecl-timelines/ecl-timelines.config.js
> +          <p class="ecl-paragraph">
Do we know a Twig expert?

2017-07-26 13:33 UTC, kalinchernev commented on framework/components/ecl-timelines/ecl-timelines.config.js
> +          <p class="ecl-paragraph">
Just pasting an idea from @emeryro (from the chat) https://twig.symfony.com/doc/2.x/tags/extends.html#block-nesting-and-scope :)

2017-07-26 13:51 UTC, yhuard commented
It should be better now ;)

2017-07-26 14:31 UTC, kalinchernev commented on framework/components/ecl-timelines/README.md
> +- **time schedule**
Indeed, it's about the content, not the design, so there's no need to add anything for it.

2017-07-26 15:14 UTC, kalinchernev approved these changes
Styles and js is good for me.
I think the contents of the item body is also ok for the moment.
Myself, I didn't find a better way with the block inheritance. I feel that for a sophisticated inheritance, it'd be better to consider block one for the whole item like in the example https://twig.symfony.com/doc/2.x/tags/extends.html#how-do-blocks-work (not sure it's worth digging this for the moment)

2017-07-27 06:12 UTC, emeryro approved these changes

2017-07-27 06:12 UTC, merged