fix(select): Fixing animation of the arrow in default select - FRONT-4348
ec-europa/europa-component-library pull request #3318
Opened 2024-04-02 11:37 UTC by planctus

2024-04-02 11:51 UTC, emeryro commented
not sure what is the issue here, but on my side the arrow animation still doesn't work as expected.
The arrow only rotate while I'm holding the mouse click, and goes back to default when I release it (regardless of the open/close status).
With the keyboard it's better, but still the arrow doesn't goes back to default when pressing escape

2024-04-02 12:03 UTC, planctus commented
The issue is that currently, if you click outside of the select to close it, the animation doesn't work anymore, in this pull request this is fixed, but it's true that we cannot fully handle the first usage of Esc, which results in closing the dropdown without animating the select, but this is a minor issue to me, considering that when you move the focus out the arrow will go back to its default position.
I read what you described about the behaviour, i do not see that, for me it works fine using the mouse, you click it opens the dropdown and rotates the icon, clicking again will close the dropdown and rotate again the icon.

Aside of this, why do we have this huge difference in the icon size for the single and the multiple select now..?

2024-04-02 12:30 UTC, emeryro commented
I don't know if we are talking about the same thing, but on my side the arrow animation doesn't work at all with the mouse (unless I keep the button pressed). Clicking outside the select or not does no difference.
simple click
![2024-04-02-select-click](https://github.com/ec-europa/europa-component-library/assets/25579221/f331e57b-27c8-41cd-8839-229d617d0143)

"long" click
![2024-04-02-select-click-long](https://github.com/ec-europa/europa-component-library/assets/25579221/be380194-bc6a-46cb-a0db-7ad6fb236bd8)

For the arrow styling, I don't know... They are indeed quite different, but I don't know if that was intentional. We'll see with the designers tomorrow

2024-04-04 11:56 UTC, planctus commented
Tried a bit more, but it seems really impossible to produce a logic that would work for all the browsers and it's also confirmed by the literature on internet, so i removed the animation from the default select.

2024-04-08 07:08 UTC, emeryro requested changes
Now I have a js error when trying to open the select with the keyboard:
![image](https://github.com/ec-europa/europa-component-library/assets/25579221/a6d7797f-d19b-455d-b9ed-1c9273c29754)

2024-04-08 07:08 UTC, emeryro commented on src/implementations/vanilla/components/select/select.js
>   * This API mostly refers to the multiple select, in the default select only three methods are actually used:
```suggestion
 * This API mostly refers to the multiple select, in the default select only two methods are actually used:
```

2024-04-09 06:37 UTC, merged