refactor(context-nav): upgrade component - INNO-732
ec-europa/europa-component-library pull request #337
Opened 2017-07-31 12:53 UTC by emeryro

# PR description

Contextual navigation component upgraded.
Component susing it (profile-topbar) has been updated too.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-07-31 13:49 UTC, yhuard commented on framework/components/ecl-context-navs/ecl-context-navs.js
> +  const nodesArray = Array.prototype.slice.call(
No need to redefine the method `queryAll` that we have in `framework/base/helpers/dom.js`

2017-07-31 13:53 UTC, yhuard requested changes
Overall, it looks very promising. Just a few remarks

2017-07-31 13:53 UTC, yhuard commented on framework/components/ecl-context-navs/ecl-context-navs.twig
> +      <span role="button" class="ecl-link ecl-link--standalone">{{ more_label }}</span>
You can't reach the "more" link with the keyboard. Maybe it would make sense to use a button here?

2017-07-31 13:53 UTC, yhuard commented on framework/components/ecl-context-navs/package.json
> +  "module": "ecl-context-navs.js",
🎉

2017-07-31 13:53 UTC, yhuard commented on framework/components/ecl-context-navs/package.json
> +    "@ec-europa/ecl-base": "^0.7.0"
`ecl-link` dependency is missing

2017-07-31 14:32 UTC, kalinchernev commented
The only additional comment I'd have after a brief look is that the interface should provide 2 more options:
- trim above - the number after which items get hidden - defaults to 5
- trim to - the number of visible items - defaults to 2
- show expander - boolean

More details in the [wiki](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Context+navigation)

2017-08-01 05:53 UTC, emeryro commented
@kalinchernev, I dont really understand why we should have all these parameters.
What we have urrently is the "limit" (ie number of items displayed before the more). If there are more items, the more button is automatically displayed.

2017-08-01 06:00 UTC, emeryro commented on framework/components/ecl-context-navs/ecl-context-navs.js
> +  const nodesArray = Array.prototype.slice.call(
Well I copy/pasted the code you made on timelines.
So there is probably the same issue there.

2017-08-01 06:03 UTC, yhuard commented on framework/components/ecl-context-navs/ecl-context-navs.js
> +  const nodesArray = Array.prototype.slice.call(
Good point, we'll need to update the timelines as well

2017-08-01 06:31 UTC, emeryro commented
@yhuard modifications have been done

2017-08-01 08:31 UTC, yhuard approved these changes

2017-08-01 08:31 UTC, merged