feat(select): Making the select all optional in the multiselect - FRONT-4462
ec-europa/europa-component-library pull request #3436
Opened 2024-06-17 13:31 UTC by planctus

2024-06-18 09:17 UTC, emeryro approved these changes

2024-07-01 06:39 UTC, emeryro requested changes
On my side I am still unable to access the buttons with arrow down; it stops at the last checkbox (on Chrome and Firefox)
Going from the button to the checkbox works fine

2024-07-01 06:44 UTC, planctus commented
It seems i forgot to push the last commit, did it now, most likely it's where i applied the changes to the arrow down navigation..

2024-07-01 07:14 UTC, emeryro approved these changes

2024-07-01 13:19 UTC, merged