refactor(forms): revamp form groups - INNO-735
ec-europa/europa-component-library pull request #357
Opened 2017-08-04 13:52 UTC by yhuard

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-08-07 14:37 UTC, kalinchernev reviewed
As I'm not sure how much of a "blocker" it is to have spacing differences between the pixels shown in the ticket, my comments are mainly around that and I'm also wondering if it's necessary to demo or regression test components which have nothing to show.

2017-08-07 14:37 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-form-groups/ecl-forms-form-groups.twig
> -<form>
Related to labels in forms, even demo such: the text input demo is not having the `ecl-form-label` and might be misleading for validating design team:

![label-text-input](https://user-images.githubusercontent.com/1923476/29030545-ab46ebaa-7b8b-11e7-9b44-0cbce21ee80c.png)

2017-08-07 14:37 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-legends/_legends.scss
> +  margin-bottom: map-get($ecl-spacing, 'm');
This one yields around 35px for me, rather than the 28px on the expectation.

2017-08-07 14:37 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-form-groups/_form-groups.scss
> +  padding-bottom: map-get($ecl-spacing, 'm');
Gives 35-ish px rather than 28px

2017-08-07 14:37 UTC, kalinchernev commented on framework/components/ecl-forms/ecl-forms-fieldsets/_fieldsets.scss
> +.ecl-fieldset {
60px spacing between last item of "Personal information" and "Group 2" on the image.

2017-08-08 05:58 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-fieldsets/test/spec/fieldsets.js
> +describe('forms-fieldset', () => {
Completely agree. I'm not even sure it should be displayed at all. There's a need to refactor the docs here. If you have any idea, I'll appreciate :)

2017-08-08 05:59 UTC, yhuard commented on framework/components/ecl-forms/ecl-forms-form-groups/ecl-forms-form-groups.twig
> -<form>
Haven't touched this one but I'll fix it, thanks!

2017-08-08 10:16 UTC, yhuard commented
I'd appreciate a second feedback now :)

2017-08-09 07:01 UTC, degliwe requested changes
Overall looks good.
I would like to suggest the creation of a special collator: "no-demo" (can be something else than a collator if you have a better idea) that will output a message (using the message component?) on the demo when there is no visible demo but only html, like form group, fieldset etc...

2017-08-09 07:44 UTC, degliwe approved these changes

2017-08-09 07:44 UTC, merged