feat(nav-menu): refactor styling - INNO-751
ec-europa/europa-component-library pull request #363
Opened 2017-08-07 13:57 UTC by yhuard

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-08-10 07:16 UTC, yhuard commented
What's left to do:
- improve the accessibility (keyboard navigation)
- use the context to build the component (no more hard coded strings)

2017-08-10 15:14 UTC, kalinchernev requested changes
Good refactoring!
Few comments below.

2017-08-10 15:14 UTC, kalinchernev commented on framework/components/ecl-navigation/ecl-navigation-menus/megamenu.js
> +const onKeydown = (node, menu) => e => {
These arrows make me smile :)

2017-08-10 15:14 UTC, kalinchernev commented on framework/components/ecl-navigation/ecl-navigation-menus/megamenu.js
> +export const megamenu = (
I like this organization of the defaults and the exports much more: less distracting, less important in the end. :+1: 
Does it make sense for the menu to be the default export?

2017-08-10 15:14 UTC, kalinchernev commented on framework/components/ecl-navigation/ecl-navigation-menus/megamenu.js
> +      node.addEventListener('click', onClick(node, menu));
Not obligatory, rather nice to have for consistency:

```js
  // REVEAL API
  return {
    init,
    destroy,
  };
```

PS new the instantiation model is much better btw, thanks!

2017-08-10 15:14 UTC, kalinchernev commented on framework/components/ecl-navigation/ecl-navigation-menus/_horizontal-menus.scss
> -  transition: 0.2s;
On the preview https://deploy-preview-363--europa-component-library.netlify.com/components/preview/ecl-navigation-menus#home the animation of the main menu doesn't work any more - is it intentional?

2017-08-10 15:14 UTC, kalinchernev commented on framework/components/ecl-navigation/ecl-navigation-menus/_horizontal-menus.scss
> -  transition: 0.2s;
At the current snapshot, the background is also missing:

![aug 10 2017 5-12 pm](https://user-images.githubusercontent.com/1923476/29177569-4556d452-7def-11e7-904d-61253329b92c.gif)

2017-08-11 08:55 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-menus/README.md
> +Using 3 words should be an exception when you want to refer to two related topics (e.g. News and events / Contracts and funding).
Actually, [it comes after the brackets](http://www.turnerink.co.uk/punctuation-tips/full-stops-inside-or-outside-of-brackets/). The doc comes from the wiki.

2017-08-11 08:56 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-menus/ecl-navigation-menus.twig
> +  {% set _css_class = _css_class ~ ' ' ~ extra_Class %}
How did I miss that? 🤔 thanks!

2017-08-11 08:57 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-menus/megamenu.js
> +export const megamenu = (
It is, at the end of the file: `export default megamenu;`

2017-08-11 09:01 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-menus/_horizontal-menus.scss
> -  transition: 0.2s;
Good catch, the missing background was a twig mistake. 

I removed the transition intentionally because it was useless (or ugly 😄)

2017-08-11 09:17 UTC, kalinchernev commented on framework/components/ecl-navigation/ecl-navigation-menus/_horizontal-menus.scss
> -  transition: 0.2s;
Ok, no prob. DT don't like animations anyway, especially when they don't follow the governance that is not discussed yet about that. A small animation in the current menu of info site was not looked well as well, so good to no animate, it's safer.

2017-08-11 11:36 UTC, kalinchernev approved these changes

2017-08-11 11:36 UTC, merged