feat(link-blocks): homogenization - INNO-757
ec-europa/europa-component-library pull request #368
Opened 2017-08-09 06:19 UTC by emeryro

# PR description

Homogenization of component

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-08-09 08:00 UTC, yhuard reviewed
I have some concerns about the `wrapper` logic here. I think the template could be simplified...

2017-08-09 08:07 UTC, kalinchernev commented on framework/components/ecl-link-blocks/ecl-link-blocks.twig
> +  {% if title != '' %}
The `if title is not [empty](https://twig.symfony.com/doc/2.x/tests/empty.html)` might be handy.

2017-08-09 08:09 UTC, kalinchernev commented on framework/components/ecl-link-blocks/ecl-link-blocks.twig
> +  ]
It's not a problem, but the indentation here takes the eyes a bit.

2017-08-09 10:00 UTC, emeryro commented
Wrapper variable has been removed

2017-08-09 12:27 UTC, yhuard reviewed
Looks nice! If the tests pass, then we can merge. But latest travis builds failed, so you may have to update some screenshots

2017-08-09 14:41 UTC, yhuard requested changes
`dropdowns collapsed dropdowns` screenshots need to be updated

2017-08-10 10:15 UTC, degliwe submitted a review, later dismissed
refactoring of link-blocks breaks the dropdown (extraClass -> extraClasses)

2017-08-10 13:09 UTC, emeryro commented
Dropdown fixed, Travis is happy

2017-08-10 13:52 UTC, yhuard approved these changes

2017-08-10 13:53 UTC, merged