feat(navigation-links): homogenization - INNO-760
ec-europa/europa-component-library pull request #372
Opened 2017-08-09 13:26 UTC by emeryro

# PR description

Homogenization of component

Note:
* I can not launch test on my environment for now, so I could not update the screenshots...

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-08-09 14:40 UTC, yhuard requested changes
Some convention naming things + the reference screenshots need to be updated

2017-08-09 14:40 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-lists/ecl-navigation-lists.twig
> +{% if extra_class is defined %}
`extra_class` should be replaced by `extra_classes` here

2017-08-09 14:40 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-lists/ecl-navigation-lists.twig
> +<nav class="ecl-navigation-list-wrapper {{ _css_class }}" {{ _extra_attributes }}>
`ecl-navigation-list-wrapper` could be integrated within `_css_class`

2017-08-09 14:40 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-lists/ecl-navigation-lists.twig
> +      {% set active_class = link.is_active is defined and link.is_active == true ? ' ecl-navigation-list__link--active' : '' %}
Internal properties should be prepended with an underscore

2017-08-10 05:54 UTC, emeryro commented on framework/components/ecl-navigation/ecl-navigation-lists/ecl-navigation-lists.twig
> +      {% set active_class = link.is_active is defined and link.is_active == true ? ' ecl-navigation-list__link--active' : '' %}
this is not an internal property

2017-08-10 13:08 UTC, emeryro commented
Screenshots updated

2017-08-11 08:50 UTC, yhuard approved these changes

2017-08-11 09:02 UTC, merged