refactor(site-header): add composition - INNO-754
ec-europa/europa-component-library pull request #395
Opened 2017-08-17 12:04 UTC by emeryro

# PR description

Refactor site header component to use composition

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-08-21 07:51 UTC, yhuard requested changes
Mainly a layout issue

2017-08-21 07:51 UTC, yhuard commented on framework/components/ecl-site-headers/ecl-site-headers.config.js
> +    political: { href: '#', label: 'Commission and its priorities' },
Will there ever only be those 2 links (political + info)?

2017-08-21 07:51 UTC, yhuard commented on framework/components/ecl-site-headers/ecl-site-headers.config.js
> +    links: [
`title`+ `links` could be grouped under `user_menu` to better distinguish them from the `political` and `info` links

2017-08-21 07:51 UTC, yhuard commented on framework/components/ecl-site-headers/_site-headers.scss
> +  padding: map-get($ecl-spacing, 's') 0;
Why? Adding this `padding` breaks the layout

2017-08-21 07:53 UTC, emeryro commented on framework/components/ecl-site-headers/ecl-site-headers.config.js
> +    political: { href: '#', label: 'Commission and its priorities' },
As far as I know, yes

2017-08-21 07:59 UTC, emeryro commented on framework/components/ecl-site-headers/_site-headers.scss
> +  padding: map-get($ecl-spacing, 's') 0;
I just moved it from .ecl-site-header to .ecl-site-header__banner, as now the site header also contains other elements (and should not have padding)

2017-08-21 08:01 UTC, emeryro commented on framework/components/ecl-site-headers/_site-headers.scss
> +  padding: map-get($ecl-spacing, 's') 0;
But in fact I only need top and bottom padding, so I will remove horizontal one

2017-08-21 08:04 UTC, emeryro commented on framework/components/ecl-site-headers/ecl-site-headers.config.js
> +    links: [
in that case, political and info should be grouped under `site_switcher` too

2017-08-21 08:04 UTC, yhuard commented on framework/components/ecl-site-headers/ecl-site-headers.config.js
> +    political: { href: '#', label: 'Commission and its priorities' },
The thing is, if one day we have to add another link, we will have to refactor the components... Maybe we can abstract it a bit by simply providing a list of links. It implies refactoring the site-switchers component as well

2017-08-21 09:07 UTC, emeryro commented
Modifications done, ready for review

2017-08-21 10:04 UTC, yhuard requested changes
Almost there

2017-08-21 10:04 UTC, yhuard commented on framework/components/ecl-site-headers/ecl-site-headers.twig
> +  {% if user_menu.links is defined %}
Beware of this (the same applies to `{% if site_switcher.political is defined and site_switcher.info is defined %}`): if `user_menu` is not defined, twig will throw errors

2017-08-21 10:04 UTC, yhuard commented on framework/components/ecl-site-headers/ecl-site-headers.twig
>    {% include '@ec-europa/ecl-site-switchers' with {
Please use the shortcut: `{% include '@ec-europa/ecl-site-switchers' with { variant: 'header' }|merge(site_switcher ) %}`

2017-08-21 10:04 UTC, yhuard commented on framework/components/ecl-site-headers/ecl-site-headers.twig
>      {% include '@ec-europa/ecl-navigation-lists' with {
You could use the shortcut as well (see my comment below)

2017-08-21 10:04 UTC, yhuard commented on framework/components/ecl-navigation/ecl-navigation-lists/_navigation.scss
> +  border-bottom-width: 0;
Out of curiosity, what's the reason?

2017-08-21 10:04 UTC, yhuard commented on framework/components/ecl-site-headers/ecl-site-headers.config.js
> +    site_switcher: {
Thanks, I appreciate :)

2017-08-21 10:09 UTC, emeryro commented on framework/components/ecl-navigation/ecl-navigation-lists/_navigation.scss
> +  border-bottom-width: 0;
Small display issue (user menu were 2 px larger than site switcher because of this border)

2017-08-22 06:36 UTC, emeryro commented
Improvement done

2017-08-22 12:31 UTC, yhuard approved these changes

2017-08-22 12:32 UTC, merged