refactor(images): make component extendable - INNO-677
ec-europa/europa-component-library pull request #407
Opened 2017-08-21 12:16 UTC by yhuard

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-08-21 12:19 UTC, yhuard commented
Wouldn't it be better if we provide an interface for the `picture` tag? 
https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/

2017-08-22 09:01 UTC, kalinchernev requested changes
About `picture` tag, it looks like a really good idea to provide it as an option!

2017-08-22 09:01 UTC, kalinchernev commented on framework/content/ecl-images/ecl-images.twig
> +{% set _css_classes = '' %}
`_css_class` is the version we have at other places.

2017-08-22 10:06 UTC, yhuard commented
@kalinchernev INNO-774 as a follow-up for the `picture` tag ;)

2017-08-22 11:44 UTC, kalinchernev approved these changes

2017-08-22 11:44 UTC, merged