fix(wdio): ignore unwanted tests - INNO-821
ec-europa/europa-component-library pull request #458
Opened 2017-09-27 12:01 UTC by emeryro

# PR description

Remove test on components set as dependencies

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

2017-09-27 12:04 UTC, HAL-Patch-INNO commented
Deploy preview ready!

Built with commit 638ecfe97d74f4e39fd6d427dabb4d8d33be0081

https://deploy-preview-458--europa-component-library.netlify.com

2017-09-27 12:06 UTC, HAL-Patch-INNO commented
Deploy preview ready!

Built with commit 0f4a309c451795aba276815651c5804244bf01e4

https://deploy-preview-458--europa-component-library.netlify.com

2017-09-27 13:46 UTC, yhuard requested changes
Something like `'**/node_modules/**'` would be better, wouldn’t it?

2017-09-28 06:18 UTC, yhuard approved these changes

2017-09-28 06:19 UTC, merged