refactor(sass): improve all components (S01E03) - INNO-1020
ec-europa/europa-component-library pull request #646
Opened 2018-04-17 13:10 UTC by emeryro

# PR description

datepicker, ...

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-04-17 13:17 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 784d82db0be72a12d39f1a84f611908bbeab9c4c

https://deploy-preview-646--europa-component-library.netlify.com

2018-04-18 06:58 UTC, yhuard requested changes

2018-04-18 06:58 UTC, yhuard commented on src/generic/generic-component-datepicker/generic-component-datepicker.scss
> +@mixin ecl-datepicker(
Please use default arguments

2018-04-18 06:58 UTC, yhuard commented on src/systems/ec/ec-component/ec-component-dropdown/ec-component-dropdown.scss
> +@include exports('ec-component-dropdown') {
Missing checks on `ec-component-button` and `ec-component-link-block`

2018-04-18 08:03 UTC, yhuard approved these changes

2018-04-18 09:00 UTC, merged