refactor(sass): improve all components (S01E06) - INNO-1020
ec-europa/europa-component-library pull request #652
Opened 2018-04-18 13:21 UTC by emeryro

# PR description

form-select, form-text-input, form-textarea, gallery-base, inpage-nav, label, lang-select-site, lang-select-page

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-04-18 13:28 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 20e882e50ec4a5664c6293dcb9652ce90a922745

https://deploy-preview-652--europa-component-library.netlify.com

2018-04-18 13:30 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 86dc4d3d09cac19d13c1dd2e9396502d064743c7

https://deploy-preview-652--europa-component-library.netlify.com

2018-04-18 13:32 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 9ae5c1a3f161e9fd8643f40f35e544c22e40879c

https://deploy-preview-652--europa-component-library.netlify.com

2018-04-19 08:44 UTC, yhuard submitted a review, later dismissed
Please remove gallery

2018-04-19 11:39 UTC, emeryro commented
Modifications on gallery have been reverted

2018-04-19 11:57 UTC, yhuard requested changes

2018-04-19 11:57 UTC, yhuard commented on src/generic/generic-component-form-select/generic-component-form-select.scss
> +    @include ecl-select-list-arrow($ecl-color-shade);
`ecl-select-list-arrow` is used before it's defined, this is not a good practice (readability)

2018-04-19 13:35 UTC, yhuard approved these changes

2018-04-19 14:11 UTC, yhuard approved these changes

2018-04-19 14:12 UTC, merged