refactor(twig): harmonize config.js - INNO-1026
ec-europa/europa-component-library pull request #656
Opened 2018-04-19 11:06 UTC by raduchiriac

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-04-19 12:13 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 3dd1afe57eb50e6131cfa270d35526b2dacdb36d

https://deploy-preview-656--europa-component-library.netlify.com

2018-04-24 12:58 UTC, yhuard requested changes
Overall it looks quite ok, I have some remarks here and there

2018-04-24 12:58 UTC, yhuard commented on docs/conventions/component.md
> +If you are not familiar with the concept of systems in ECL, first have a look at [the system documentation](../systems).
On GitHub, the link is not valid anymore. The question (still open) is where should we store the docs? on GitHub vs on site?

2018-04-24 12:58 UTC, yhuard commented on src/generic/generic-component-message/data/demo--error.js
> +  srOnly: 'Error message',
`srOnly`does not exist anymore...

2018-04-24 12:58 UTC, yhuard commented on src/generic/generic-component-navigation-list/data/demo.js
> +module.exports = {
you could call this file `shared.js` (it'snot context for an actual demo)

2018-04-24 12:58 UTC, yhuard commented on src/generic/generic-component-social-media-link/data/demo.js
> +module.exports = {
`shared.js`:)

2018-04-24 12:58 UTC, yhuard commented on src/generic/generic-component-table/variants.js
> +const contextDefault = require('./data/demo--default');
this file should not exist anymore

2018-04-25 09:50 UTC, yhuard requested changes

2018-04-25 09:50 UTC, yhuard commented on src/generic/generic-component-message/data/demo--info.js
> -  srOnly: 'Informative message',
I was expecting that you to rename it `screen_reader_description` instead of `srOnly`, not to delete it...

2018-04-25 12:11 UTC, yhuard approved these changes

2018-04-25 13:28 UTC, yhuard approved these changes

2018-04-25 13:28 UTC, merged