refactor(config): harmonize config.js, pt.2 - INNO-1026
ec-europa/europa-component-library pull request #666
Opened 2018-04-23 12:20 UTC by raduchiriac

Affected components:
- [ ] label
- [ ] lang-select
- [ ] link
- [ ] list-item
- [ ] listing

2018-04-23 12:28 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 503e70196f7fee33e95ee424b2f331b8f4375e4f

https://deploy-preview-666--europa-component-library.netlify.com

2018-04-24 07:19 UTC, emeryro submitted a review, later dismissed
A few modifications to be done:
- update config files for ec components
- remove *.config.js in generic components
- context files in generic components should be named `demo--*.js`, not `data--*.js`

2018-04-25 06:34 UTC, yhuard requested changes
seems like you have mixed the `component-listing` data

e.g. "two-columns" was demoed with `itemsThumbnails`, now it is demoed with `itemsDefault`

2018-04-25 09:45 UTC, yhuard approved these changes

2018-04-25 09:47 UTC, merged