fix(patches): apply some patches from Open Europa - INNO-1090
ec-europa/europa-component-library pull request #704
Opened 2018-06-19 13:35 UTC by emeryro

# PR description

Patches applied:
- ec-component-dialog+1.0.0.patch: update default value of parameter
- ec-component-language-list+1.0.1.patch: use active language for language list button

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-06-19 13:43 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 1b31e5993d5c020bdd413cc4a8ac9429ff9068bb

https://deploy-preview-704--europa-component-library.netlify.com

2018-06-20 07:28 UTC, yhuard requested changes
Please update the generic templates `generic-component-language-list.twig` and `generic-component-dialog.twig` as well

2018-06-20 07:28 UTC, yhuard commented on src/systems/ec/ec-component/ec-component-language-list/ec-component-language-list.twig
> +    {% for language in _languages %}
should be `_language` instead of `language`

2018-06-20 07:54 UTC, yhuard approved these changes

2018-06-20 09:41 UTC, merged