fix(list-item): improve code quality - INNO-1102
ec-europa/europa-component-library pull request #713
Opened 2018-06-28 12:39 UTC by raduchiriac

# PR description

https://github.com/ec-europa/europa-component-library/pull/707/files#diff-1854779ba629acf4cd6d0f16119f452bR103
> `.ecl-list-item-navigation .ecl-list-item_link .ecl-list-item_title { }`
Flatten things `.ecl-list-item-link` is not necessary

https://github.com/ec-europa/europa-component-library/pull/707/files#diff-1854779ba629acf4cd6d0f16119f452bR127
`@include ecl-media-breakpoint-down(md) {`
we can get rid of it for now

https://github.com/ec-europa/europa-component-library/pull/707/files#diff-33295e9389f976a1d94791f3f84d2b4aR93
`3n + 0` = `3n`

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-06-28 12:47 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit fc265e6efba24ae0f490255a733cc8c757089ac1

https://deploy-preview-713--europa-component-library.netlify.com

2018-06-29 09:22 UTC, yhuard requested changes
The "Flatten things `.ecl-list-item-link` is not necessary" part is missing

2018-06-29 09:22 UTC, yhuard commented on src/generic/generic-component-list-item/generic-component-list-item.scss
> -
In fact, it should have been the other way around. In mobile-first, you should never use `ecl-media-breakpoint-down`, but always use `ecl-media-breakpoint-up`. The description in the ticket was wrong. Sorry for that

2018-06-29 14:06 UTC, yhuard approved these changes

2018-06-29 14:06 UTC, merged