refactor(icons): revamp icons for ECL 2.x
ec-europa/europa-component-library pull request #726
Opened 2018-07-11 06:09 UTC by emeryro

# PR description

Improve the way icons are managed in ECL

*File structure*
- Social media icons have been moved out of component, and put in a global `resources` folder (one per system) 

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-07-11 06:17 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit a0bfefaaeddf0eaa8257da2711293e8d556ec706

https://deploy-preview-726--europa-component-library.netlify.com

2018-07-23 15:36 UTC, raduchiriac commented on src/systems/ec/ec-resources/icons/ui/if_gear_298781.svg
> +<title>if_gear_298781</title>
Can we rename this `cog` as per https://webgate.ec.europa.eu/CITnet/jira/browse/INNO-953 or more preferably `gear`?

2018-07-24 08:47 UTC, raduchiriac commented on src/systems/eu/eu-style/eu-style-icon/eu-style-icon.config.js
> +    <div class="ecl-u-d-inline-flex">
What about a `.ecl-u-align-items-center` here?

2018-07-24 09:22 UTC, raduchiriac commented
Everything looks fine from what I could test. Good work :+1: 

Things we don't have to forget about:
- future of `generic-style-icon/fonts`
- future of `ec-resources/icons/social/` and `/ui`

2018-07-24 11:31 UTC, raduchiriac requested changes
Can you please fix this last thing? `error  Unable to resolve path to module '@ecl/generic-component-button/data/demo'  import/no-unresolved`

2018-07-24 11:47 UTC, merged