feat(showcase): showcase for buttons
ec-europa/europa-component-library pull request #746
Opened 2018-08-01 13:39 UTC by emeryro

# PR description

PoC of component showcase.
Only buttons are displayed

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-08-02 06:48 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 5d0c61fae15159418fb4b6d8cab42a2c674ad8b1

https://deploy-preview-746--europa-component-library.netlify.com

2018-08-02 08:23 UTC, degliwe requested changes
- provide default styling for iframe (1px black border)
- make the iframe resizable
- provide the link to "full page" display automatically
- default iframe should be full width (only the height is needed)

2018-08-07 12:55 UTC, degliwe submitted a review, later dismissed
- limit min width and height
- keep "full page preview" link below the showcase

2018-08-08 13:04 UTC, yhuard approved these changes

2018-08-08 13:05 UTC, merged