feat(storybook): create PoC with storybook - INNO-1165
ec-europa/europa-component-library pull request #762
Opened 2018-08-09 13:38 UTC by yhuard

Add React components + storybook.

Use the React components in the docs directly.

2018-08-09 13:49 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 6fd7a09fdee2b1d720ee0463066348521b0ce45b

https://deploy-preview-762--europa-component-library.netlify.com

2018-08-13 06:28 UTC, degliwe requested changes
- displaying/hiding navigation adds an extra iframe after each click
- the displayed markup isn't vanilla html

2018-08-13 11:25 UTC, degliwe requested changes
- iframe not inserted on page direct access (but inserted on tab switch)
- remove the resizable on the showcase
- rename "open in storybook" to "open in playground"
- open storybook in a new tab

2018-08-13 12:16 UTC, degliwe approved these changes

2018-08-13 12:16 UTC, merged