chore(twig): extract twig templates from vanilla implementations - INNO-1166
ec-europa/europa-component-library pull request #773
Opened 2018-08-16 10:49 UTC by yhuard

…

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-08-20 12:16 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 42e7f781e8b5e6faf002f8a9cd04274d4f0de5fe

https://deploy-preview-773--europa-component-library.netlify.com

2018-08-20 13:13 UTC, emeryro reviewed
To be cleanup up (in a follow-up ticket)
- js files is twig components (could use vanilla)
- demo data files in vanilla

2018-08-20 13:14 UTC, emeryro requested changes
just a small thing:
design tokens for colors are not up to date in generic (missing black and white)

2018-08-21 05:55 UTC, emeryro approved these changes

2018-08-21 05:55 UTC, merged