chore(website): revamp website architecture - INNO-1171
ec-europa/europa-component-library pull request #780
Opened 2018-08-22 14:05 UTC by yhuard

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-08-22 14:13 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 07f20906794cd0834dc59e0e88bc3d7d007a955e

https://deploy-preview-780--europa-component-library.netlify.com

2018-08-23 06:30 UTC, degliwe requested changes
It would be easier to read with the status before the name.

2018-08-23 06:42 UTC, yhuard commented
@degliwe fixed

2018-08-23 06:50 UTC, degliwe approved these changes

2018-08-23 06:53 UTC, merged