feat(tag): implement new specs for tag - INNO-1201
ec-europa/europa-component-library pull request #804
Opened 2018-09-06 13:38 UTC by yhuard

# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-09-10 07:46 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 94d842803b7f37ab7786ea422498b761a9d517af

https://deploy-preview-804--europa-component-library.netlify.com

2018-09-17 13:34 UTC, degliwe requested changes

2018-09-17 13:34 UTC, degliwe commented on src/systems/ec/specs/components/tag/docs/code.mdx
> +    href="/example.html#tag"
should be example#tag

2018-09-17 13:34 UTC, degliwe commented on src/systems/ec/specs/components/tag/docs/code.mdx
> +<Playground playgroundLink="/storybook/ec/index.html?selectedKind=Tag&selectedStory=default&stories=0">
wrong url

2018-09-17 13:34 UTC, degliwe commented on src/systems/ec/specs/components/tag/docs/code.mdx
> +<Playground playgroundLink="/storybook/ec/index.html?selectedKind=Tag&selectedStory=default&stories=0">
wrong url

2018-09-17 13:34 UTC, degliwe commented on src/systems/ec/implementations/react/packages/tag/stories/index.jsx
> +      href={text('Link', '#')}
href is breaking storybook, should be `/example#tag`

2018-09-24 06:30 UTC, degliwe approved these changes

2018-09-24 06:48 UTC, merged