feat(icon-tokens): tokenize icons by category - INNO1188
ec-europa/europa-component-library pull request #810
Opened 2018-09-11 10:24 UTC by yhuard

- Refactor icons workflow and component.
- Automatically sanitize icons (extracts defs)
- Rename icons: e.g. from `Icon_Facebook` to `facebook`
- IDs take the set into account: e.g. `facebook` in "branded" => ID = `branded--facebook`
- Offer a couple of simple transformations (rotate, flip)

2018-09-11 10:30 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 529e5510483b9424e2b08c0d3d5acc055d7ec262

https://deploy-preview-810--europa-component-library.netlify.com

2018-09-17 07:13 UTC, degliwe requested changes

2018-09-17 07:13 UTC, degliwe commented on src/systems/generic/implementations/vanilla/generic-style-icon/generic-style-icon.scss
> +  .ecl-icon--rotate-180 {
the file should be renamed (not style but component)

2018-09-17 12:26 UTC, degliwe approved these changes

2018-09-17 12:28 UTC, merged