Feat/site switcher  inno 1219
ec-europa/europa-component-library pull request #815
Opened 2018-09-20 07:03 UTC by degliwe

2018-09-20 07:49 UTC, yhuard requested changes

2018-09-20 07:49 UTC, yhuard commented on src/systems/ec/implementations/react/packages/site-switcher/SiteSwitcher.jsx
> +            <a className="ecl-link ecl-site-switcher__link" href={item1.href}>
Better use a `<Link>` here ;)

2018-09-20 07:49 UTC, yhuard commented on src/systems/ec/implementations/react/packages/site-switcher/SiteSwitcher.jsx
> +  item1: item,
why not make an array of items? if there are always 2 items, let's try to give them a better name than `item1` and `item2` 👼

2018-09-20 07:49 UTC, yhuard commented on src/systems/ec/implementations/react/packages/site-switcher/SiteSwitcher.jsx
> +    href: '../../example.html#',
better leave it empty by default

2018-09-20 07:49 UTC, yhuard commented on src/systems/ec/implementations/react/packages/site-switcher/SiteSwitcher.jsx
> +    label: 'Policies, information and services',
better leave it empty (check INNO-1118)

2018-09-20 07:49 UTC, yhuard commented on src/systems/ec/implementations/react/packages/site-switcher/package.json
> +    "@ecl/ec-react-component-button": "^2.0.0-alpha.0",
why those 2 dependencies?

2018-09-24 10:34 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit e399edbcb87ef4c7be310c0650749dc1025a4757

https://deploy-preview-815--europa-component-library.netlify.com

2018-09-24 10:43 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit db558abd571c32a166a0035a45e747f7de9f52a9

https://deploy-preview-815--europa-component-library.netlify.com

2018-09-24 13:17 UTC, yhuard requested changes
a few things to enhance here and there

2018-09-24 13:17 UTC, yhuard commented on src/systems/ec/implementations/react/packages/site-switcher/SiteSwitcher.jsx
> +/* eslint-disable import/no-extraneous-dependencies */
don't disable this rule here

2018-09-24 13:17 UTC, yhuard commented on src/systems/ec/implementations/react/packages/site-switcher/SiteSwitcher.jsx
> +  variant: 'header',
why not empty by default?

2018-09-24 13:17 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher.scss
> +      flex-grow: initial;
`initial` is not supported by IE11

2018-09-24 13:17 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher.scss
> +        float: right;
why not use `justify-content: flex-end;`? then no more floats -> no more `clear: both` after -> cleaner

2018-09-24 13:17 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher.scss
> +      border: 10px solid rgba(0, 68, 148, 0);
please use a design prop instead of a magic color

2018-09-25 09:11 UTC, yhuard requested changes

2018-09-25 09:11 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher.scss
> +    font-weight: bold;
we have a design prop for that

2018-09-25 09:11 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher.scss
> +      content: ' ' !important;
is `!important` really needed?

2018-09-25 09:11 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-site-switcher/ec-component-site-switcher.scss
> +      flex-grow: unset;
`unset` -> `0`

2018-09-25 09:48 UTC, yhuard approved these changes

2018-09-25 09:48 UTC, merged