feat(language-list-ec): implement EC language list - INNO-1180
ec-europa/europa-component-library pull request #827
Opened 2018-09-28 10:10 UTC by yhuard

EC version of the language list component.

Contains some small fixes for the EU version as well.

2018-09-28 10:17 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit dd4c4b4abf51c233541a5137642aea001427259e

https://deploy-preview-827--europa-component-library.netlify.com

2018-10-01 06:42 UTC, degliwe requested changes

2018-10-01 06:42 UTC, degliwe commented on src/systems/ec/specs/components/language-list/demo/data--splash.js
> +// Simple content for demo
Languages order should follow https://github.com/ec-europa/europa-component-library/blob/master/src/generic/generic-component-language-list/languages.json

2018-10-01 06:42 UTC, degliwe commented on src/systems/ec/specs/components/language-list/demo/data--overlay.js
> +// Simple content for demo
Languages order should follow https://github.com/ec-europa/europa-component-library/blob/master/src/generic/generic-component-language-list/languages.json

2018-10-01 07:37 UTC, degliwe approved these changes

2018-10-01 07:37 UTC, merged