feat(cards): apply new specifications
ec-europa/europa-component-library pull request #829
Opened 2018-10-01 09:28 UTC by emeryro

# PR description

Apply [new component specifications](https://webgate.ec.europa.eu/CITnet/confluence/x/nZNOMQ)

2018-10-01 09:37 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 8953b4ef98ccebd14bac36c96873c1bd1a48d548

https://deploy-preview-829--europa-component-library.netlify.com

2018-10-04 09:52 UTC, yhuard requested changes
reviewed EC, most of the remarks are also valid for EU

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/react/packages/card/stories/Template.jsx
> +  return (
If you're using an `ecl-row`, please wrap the template within an `ecl-container` and remove the `margin: 0` from the `ul`

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card.scss
> +    background-color: $background-card;
`box-sizing: border-box;` is missing

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card.scss
> +    padding-right: $ecl-spacing-s;
the paddings should take the border into account

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card.scss
> +    margin-top: $ecl-spacing-s;
the margin should take the border into account

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card.scss
> +      margin-top: $ecl-spacing-l;
don't forget to take the border into account

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card.scss
> +    margin-bottom: $ecl-spacing-s;
don't forget the border

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/ec-component-card.scss
> +@include exports('eu-component-card') {
`'eu-component-card'` -> `'ec-component-card'`

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/package.json
> +  "description": "EU Card",
-> `ECL EC Card`
btw, doesn't it depend on the link component?

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-preset-full/_imports.scss
> +@import '@ecl/ec-component-card/ec-component-card';
Don't forget to also add the component to the preset's package.json dependencies

2018-10-04 09:52 UTC, yhuard commented on src/systems/ec/specs/components/card/package.json
> +  "description": "ECL EC Logo Specs",
why "Logo"?

2018-10-04 12:28 UTC, yhuard requested changes
2 (optional) enhancements

2018-10-04 12:28 UTC, yhuard commented on src/systems/ec/specs/components/card/docs/code.mdx
> +<Playground playgroundLink="/storybook/ec/index.html?selectedKind=Card&selectedStory=card&stories=0">
You can use the new syntax here (check https://github.com/ec-europa/europa-component-library/blob/next-v2/src/systems/ec/specs/components/hero-banner/docs/code.mdx#L13)

2018-10-04 12:28 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-card/package.json
> +    "@ecl/ec-component-link": "^2.0.0-alpha.0",
if you check the imports in sass for those dependencies, it's even better :)

2018-10-04 12:57 UTC, yhuard approved these changes

2018-10-04 13:03 UTC, merged