fix(image): add example image - INNO-1257
ec-europa/europa-component-library pull request #884
Opened 2018-10-15 13:16 UTC by emeryro

# PR description

The image we were using as example has been removed. A new image has been set; not it doesn't rely on external site.

2018-10-15 13:22 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 944a60eb6d3c600500e061bec74d63a8651510fd

https://deploy-preview-884--europa-component-library.netlify.com

2018-10-15 13:22 UTC, yhuard requested changes

2018-10-15 13:22 UTC, yhuard commented on src/systems/ec/specs/components/card/demo/data--card.js
> +const demoImage = require('@ecl/ec-resources-example/example-image.jpg');
Specs are meant to be generic. You're importing a jpg in a JS file. It implies people will have to use webpack or another module bundle in order to load this file...

Can you move the "require logic" outside of this file? Only the path to the image should remain here. :)

2018-10-16 07:48 UTC, yhuard requested changes

2018-10-16 07:48 UTC, yhuard commented on src/systems/ec/resources/example/package.json
> +  "version": "2.0.0-alpha.1",
please update version number :)

edit: everywhere

2018-10-16 08:28 UTC, emeryro commented
Ready for another round

2018-10-16 08:32 UTC, yhuard approved these changes

2018-10-16 08:32 UTC, merged