feat(page-banner): add component - INNO-1230
ec-europa/europa-component-library pull request #894
Opened 2018-10-17 07:26 UTC by emeryro

# PR description

Create new component, based on [specifications](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Page+banner+-+Design+specifications)

2018-10-17 07:38 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 398c6a831ca059a0cf1ca05dca6a6036a00abc5f

https://deploy-preview-894--europa-component-library.netlify.com

2018-10-17 13:09 UTC, degliwe requested changes
- Can we make the markup more semantic?
- The wrapper could be  `<section />`
- The title could use a `<h*/>`
- ...

2018-10-18 09:08 UTC, yhuard requested changes

2018-10-18 09:08 UTC, yhuard commented on src/systems/ec/implementations/react/packages/page-banner/PageBanner.jsx
> +    <section className={classNames} {...props}>
```suggestion
    <section {...props} className={classNames}>
```

2018-10-18 09:08 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-page-banner/ec-component-page-banner.scss
> +    height: (1/4) * 100vw;
yeah, or just `25vw` :)

```suggestion
    height: 25vw;
```

2018-10-18 12:58 UTC, emeryro commented on src/systems/ec/implementations/vanilla/packages/ec-component-page-banner/ec-component-page-banner.scss
> +    height: (1/4) * 100vw;
yes, it works too, but I find more explicit this way (we see the ratio directly)

2018-10-18 13:13 UTC, yhuard approved these changes

2018-10-18 13:13 UTC, merged