feat(typography): add paragraphs and headings - 1271
ec-europa/europa-component-library pull request #938
Opened 2018-10-25 13:13 UTC by emeryro

# PR description

Add missing paragraph sizes and headings, according to [the specifications](https://next-v2--europa-component-library.netlify.com/ec/guidelines/typography/)

Also use rem for line-heights

2018-10-25 13:19 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 196b6e95d8d4a91a47e05da194af9fcc99d5f5c6

https://deploy-preview-938--europa-component-library.netlify.com

2018-10-25 13:51 UTC, yhuard requested changes
A small change is requested (both EC and EU).

2018-10-25 13:51 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-tag/ec-component-tag.scss
> +        2 * $ecl-spacing-xs + ($ecl-font-size-s * $ecl-line-height-s) / 1rem
```suggestion
        2 * $ecl-spacing-xs + $ecl-line-height-s
```

the line-height is now the right value (we don't need to take the font-size into account)

2018-10-29 07:36 UTC, yhuard requested changes

2018-10-29 07:36 UTC, yhuard commented on src/systems/eu/implementations/vanilla/packages/eu-component-tag/eu-component-tag.scss
> +        2 * $ecl-spacing-xs + ($ecl-font-size-s * $ecl-line-height-s) / 1rem
please fix this one too

2018-10-29 07:36 UTC, yhuard commented on src/systems/eu/implementations/react/packages/typography/stories/Index.jsx
>  storiesOf('Typography', module)
can you prefix it with "Utilities"? i.e. `storiesOf('Utilities/Typography', module)`
it makes it easier to find stories (note: we should do it for other stories as well)

2018-10-31 08:23 UTC, yhuard submitted a review, later dismissed

2018-10-31 08:23 UTC, yhuard commented on src/systems/ec/specs/utilities/typography/docs/code.mdx
> +  selectedKind="Typography"
please update the `selectedKind` -> `Utilities/Typography` wherever it's needed

2018-11-22 10:48 UTC, degliwe approved these changes

2018-11-22 10:49 UTC, merged