feat(message): apply new specs
ec-europa/europa-component-library pull request #944
Opened 2018-10-29 13:33 UTC by emeryro

# PR description

Apply [new specifications](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Messages+-+Design+Specifications) for message component

2018-10-29 13:39 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 49dcba4afc3bac67f7ef86202540ab99063c75a3

https://deploy-preview-944--europa-component-library.netlify.com

2018-11-26 14:38 UTC, yhuard requested changes
- the generated code outputs a "submit" type for the close button, it should be `type="button"`
- the "close" behaviour is missing. I think there should be a basic generic implementation of this behaviour using the `data-ecl-*` attribute that simply removes the element from the DOM on click. TBD if needed

2018-11-27 11:28 UTC, yhuard submitted a review, later dismissed

2018-11-27 11:28 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-message/ec-component-message.js
> +    if (this.element.parentNode) {
The action on the DOM should be handled by React (as it's done in the breadcrumb) -> you could pass a new parameter to the constructor's options which is a callback that is called (if defined) in `handleClickOnClose`

2018-11-29 14:27 UTC, degliwe approved these changes

2018-11-29 14:28 UTC, merged