feat(eu-menu): add component - INNO-1202
ec-europa/europa-component-library pull request #946
Opened 2018-10-30 13:07 UTC by emeryro

# PR description

Add component according to [specifications](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Menu_eu+Design+Specifications)

2018-10-31 14:33 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit b181953b86b6a0a09b0fbf0e3179d406fc46079d

https://deploy-preview-946--europa-component-library.netlify.com

2019-07-03 13:37 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-preset-legacy-website/package.json
> +    "@ecl/ec-component-menu-legacy": "^2.7.0"
should be a `devDependencies` (to be consistent with `@ecl/ec-preset-dev` and others)

2019-07-03 13:49 UTC, yhuard submitted a review, later dismissed

2019-07-04 07:42 UTC, degliwe requested changes

2019-07-04 07:42 UTC, degliwe commented on src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.scss
> +    transform: rotate(45deg) translate(-8px, -8px);
```suggestion
    transform: rotate(45deg) translate(-9px, -8px);
```

2019-07-04 07:42 UTC, degliwe commented on src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.scss
> +    transform: rotate(-45deg) translate(-9px, 6px);
```suggestion
    transform: rotate(-45deg) translate(-8px, 6px);
```

2019-07-04 07:42 UTC, degliwe commented on src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.scss
> +
```suggestion
  .ecl-menu__subitem {
    padding-right: $ecl-spacing-m ;
    box-sizing: border-box;
  }
```

2019-07-04 11:37 UTC, yhuard requested changes

2019-07-04 11:37 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.js
> +class Menu {
```suggestion
export class MenuLegacy {
```

2019-07-04 11:37 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-menu-legacy/ec-component-menu-legacy.js
> +export default Menu;
```suggestion
export default MenuLegacy;
```

2019-07-04 11:37 UTC, yhuard commented on src/systems/eu/implementations/vanilla/packages/eu-component-menu-legacy/eu-component-menu-legacy.js
> +class Menu {
```suggestion
export class MenuLegacy {
```

2019-07-04 11:37 UTC, yhuard commented on src/systems/eu/implementations/vanilla/packages/eu-component-menu-legacy/eu-component-menu-legacy.js
> +export default Menu;
```suggestion
export default MenuLegacy;
```

2019-07-04 12:51 UTC, yhuard approved these changes

2019-07-04 13:08 UTC, degliwe approved these changes

2019-07-04 13:08 UTC, merged