feat(social-media-share): add component - INNO-1264
ec-europa/europa-component-library pull request #950
Opened 2018-11-07 13:48 UTC by planctus

# PR description

This pull request is introducing the social-media-share component as an independent one.
It has only been placed in the ec system, although i believe this is a common one, likely to be shared with the EU system as well.
Being this a component "served" by webtools i had many doubts regarding the way we would, should provide it, for now and only for demo purposes i added the needed styles for the buttons to appear as they should, this would require the definition of the list of supported social networks to be able to define the style (background, basically) for all of them.
I added the vanilla, the react and the specs packages, it works apparently fine in the storybook but when i move into the website i see that the "playground" and "full screen" links are not working.

Furthermore i noticed that because of the outline we have on focused elements we needed (only for demoing) purposes, to add an element to create a bit of space on the left, this was "easy" in storybook, could not find a proper way to do the same with the website.
Same thing for an "additional" css to be used only for demoing purposes, i was able to set it for storybook in a "clean" way, didn't find a way to easily do it in the website.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

2018-11-07 14:13 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit d65f73b7667a706db069f16f12bc9be6ea31b218

https://deploy-preview-950--europa-component-library.netlify.com

2018-11-14 10:29 UTC, degliwe commented on src/systems/ec/implementations/react/packages/social-media-share/stories/Index.jsx
> +import '@ecl/ec-specs-social-media-share/demo/demo.css';
Can't we get rid of it?

2018-11-14 10:29 UTC, degliwe commented on src/systems/ec/implementations/react/packages/social-media-share/SocialMediaShare.jsx
> +      <ul className="ecl-social-media-share__list">
Does not provide the label "Share this page". Without it it's impossible to know what those buttons are for.

2018-11-14 12:26 UTC, planctus commented on src/systems/ec/implementations/react/packages/social-media-share/stories/Index.jsx
> +import '@ecl/ec-specs-social-media-share/demo/demo.css';
mmh..yes, sure. is that i wanted to fix that little problem regarding the outline in storybook and then i started wondering about how to to do this without affecting the component, that's the reason why of this demo.css. Plus with that i was fixing a bit the demo for the google icon which is "broken" but surely this needs to be fixed properly by replacing the svg, i'll push without this "helper" css, these two issues will pop up, though.

2018-11-14 12:27 UTC, planctus commented on src/systems/ec/implementations/react/packages/social-media-share/SocialMediaShare.jsx
> +      <ul className="ecl-social-media-share__list">
Yeah, but that was on purpose, because in the specifications there is no "share this page". I'll add it, anyhow.

2018-11-15 10:36 UTC, planctus commented
@degliwe, i pushed the requested changes, hopefully.. ;)

2018-11-15 10:42 UTC, degliwe commented on src/systems/ec/implementations/react/packages/social-media-share/SocialMediaShare.jsx
> +      <ul className="ecl-social-media-share__list">
You are right. the specs are incomplete. I've reported it (see my comment on the specs page)
Let's wait for new specs.

2018-11-15 14:22 UTC, emeryro commented
Drone reports a few issues to be fixed: https://drone.fpfis.eu/ec-europa/europa-component-library/2951/5 (don't mind the warnings)

2018-11-16 09:47 UTC, planctus commented
Thanks @emeryro for noticing that, first time i access the "drone" builds. Should be fixed now, but i see that when i go "fullscreen" in the social media share component, i lose the description...

2018-12-03 14:38 UTC, planctus commented
The g+ icons have been replaced with new ones, the ones specified here: https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Social+Media+-+Share+%7C+Design+Specifications
Also the ones in the "social icons" here:
https://webgate.ec.europa.eu/CITnet/confluence/pages/viewpage.action?pageId=837977554
are going to be updated, the new ones completely replace the old ones, basically.

2018-12-05 14:55 UTC, emeryro submitted a review, later dismissed
A few margin tricks should be added to fix following cases:

- horizontal display, lots of items: vertical spacing missing. This is not in the specs, so either we ask for a specific value, or we use the one from vertical display.
![image](https://user-images.githubusercontent.com/25579221/49521327-820d4480-f8a5-11e8-9c31-ab05f118c221.png)

- vertical display: due to bottom margin on items, the components takes extra space below (red area). This could be a little tricky to solve... maybe negative margin could work...
![image](https://user-images.githubusercontent.com/25579221/49521541-f3e58e00-f8a5-11e8-8824-f6bedf8d2421.png)

2018-12-11 10:10 UTC, emeryro commented
This is almost good, just a few last things:

- put the text `(work in progress)` in src/website/src/pages/ec/components/social-media-share/docs/usage.md (similar to what we have on other components)
- set the status to `ready` in src/website/src/pages/ec/components/social-media-share/index.md
- add the EU version (copy/paste of everything)

2018-12-12 10:44 UTC, yhuard requested changes
A few remarks here and there (also valid for EU) but overall it looks good :)

2018-12-12 10:44 UTC, yhuard commented on src/systems/ec/implementations/react/packages/social-media-share/package.json
> +{
Please make the package private ;-) (check the other React packages, they're all private now)

2018-12-12 10:44 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-social-media-share/ec-component-social-media-share.scss
> +  @include ecl-icon-rollover(ecl-social-media-share);
why not including it first? (and thus avoiding the stylelint error)

2018-12-12 10:44 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-social-media-share/package.json
> +    "@ecl/ec-component-icon": "^2.0.0"
it depends on `@ecl/ec-component-link` too, doesn't it?

2018-12-12 10:44 UTC, yhuard commented on src/systems/ec/specs/components/social-media-share/demo/data.js
> +        {
the problem with this structure is that you have to remember that the first item is the default icon and the second icon is the icon on hover... but what happens if you add a third icon?

2018-12-17 09:55 UTC, planctus commented
@yhuard, thanks for the review, i should have made the requested changes, for the icons we are not relying on the array index anymore, see if it's better like this.

2018-12-17 13:51 UTC, yhuard approved these changes

2018-12-17 13:52 UTC, merged