feat(contextual-navigation): apply new specs - INNO-1236
ec-europa/europa-component-library pull request #954
Opened 2018-11-15 10:31 UTC by emeryro

# PR description

Update component by applying new [specifications](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Contextual+navigation+-+Design+specifications)

2018-11-15 10:40 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit 6766ef80f4de2990f40914179c33a419c0c0db1a

https://deploy-preview-954--europa-component-library.netlify.com

2018-11-26 17:33 UTC, yhuard requested changes
Overall it looks good. I've noticed some small details that can be fixed

2018-11-26 17:33 UTC, yhuard commented on src/systems/ec/implementations/react/packages/contextual-navigation/ContextualNavigation.jsx
> +    this.state = {};
why do you initialize a state here?

2018-11-26 17:33 UTC, yhuard commented on src/systems/ec/implementations/react/packages/contextual-navigation/ContextualNavigation.jsx
> +          {items.map((item, key) => (
`index` is more comprehensible than `key`

2018-11-26 17:33 UTC, yhuard commented on src/systems/ec/implementations/react/packages/contextual-navigation/ContextualNavigation.jsx
> +  author: PropTypes.string,
`author` is not used

2018-11-26 17:33 UTC, yhuard commented on src/systems/ec/implementations/react/packages/contextual-navigation/ContextualNavigation.jsx
> +        <Link
"More" is a button, not a link

2018-11-27 14:11 UTC, yhuard requested changes
React should handle the DOM mutations

2018-11-30 09:59 UTC, yhuard requested changes

2018-11-30 09:59 UTC, yhuard commented on src/systems/ec/implementations/react/packages/contextual-navigation/stories/Index.jsx
> +        if (context.vanillaMessage) {
`vanillaMessage` -> `vanillaContextualNavigation`

2018-11-30 10:05 UTC, emeryro commented on src/systems/ec/implementations/react/packages/contextual-navigation/stories/Index.jsx
> +        if (context.vanillaMessage) {
indeed...

2018-11-30 10:20 UTC, yhuard approved these changes

2018-11-30 10:22 UTC, merged