feat(expandable): add expandable - INNO-1288
ec-europa/europa-component-library pull request #973
Opened 2018-12-07 15:01 UTC by emeryro

# PR description

Add expandable, based on [specifications](https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Expandable+-+Design+specifications)

2018-12-07 15:07 UTC, HAL-Patch-INNO commented
Deploy preview for *europa-component-library* ready!

Built with commit c96cae8bfc1ecb2600636bebef4134f5ef9a8981

https://deploy-preview-973--europa-component-library.netlify.com

2018-12-10 10:14 UTC, yhuard reviewed
PR on hold

2018-12-10 10:14 UTC, yhuard commented on src/systems/ec/implementations/vanilla/packages/ec-component-expandable/ec-component-expandable.scss
> +  :not(.no-js) .ecl-expandable__content[aria-hidden='true'] {
instead of `:not(.no-js)`, you can use `.js`

2019-01-07 13:33 UTC, yhuard requested changes
there might have been a misunderstanding: an expandable never involves a link (it's not the purpose of a link to trigger expandables)

2019-01-18 08:28 UTC, yhuard requested changes
one last thing and then I think we're good: React packages must be private (see https://github.com/ec-europa/europa-component-library/blob/v2/src/systems/ec/implementations/react/packages/button/package.json)

2019-01-18 08:50 UTC, emeryro commented
React packages are now private

2019-01-18 08:53 UTC, yhuard approved these changes

2019-01-18 08:58 UTC, merged